package alicloudroscdkesa

import (
	_init_ "github.com/alibabacloud-go/ros-cdk/alicloudroscdkesa/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkcore"
	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkesa/internal"
	"github.com/aws/constructs-go/constructs/v3"
)

// This class encapsulates and extends the ROS resource type `ALIYUN::ESA::OriginRule`.
type OriginRule interface {
	alicloudroscdkcore.Resource
	IOriginRule
	// Attribute ConfigId: Back-to-source rule configuration ID.
	AttrConfigId() interface{}
	// Attribute ConfigType: The configuration type.
	//
	// You can use this parameter to check the global configuration or rule configuration.
	AttrConfigType() interface{}
	// Attribute DnsRecord: Overwrite the DNS resolution record of the origin request.
	AttrDnsRecord() interface{}
	// Attribute Follow302Enable: Return Source 302 follow switch.
	AttrFollow302Enable() interface{}
	// Attribute Follow302MaxTries: 302 follows the upper limit of the number of times, with a value range of [1-5].
	AttrFollow302MaxTries() interface{}
	// Attribute Follow302RetainArgs: Retain the original request parameter switch.
	AttrFollow302RetainArgs() interface{}
	// Attribute Follow302RetainHeader: Retain the original request header switch.
	AttrFollow302RetainHeader() interface{}
	// Attribute Follow302TargetHost: Modify the source host after 302.
	AttrFollow302TargetHost() interface{}
	// Attribute OriginHost: The HOST carried in the back-to-origin request.
	AttrOriginHost() interface{}
	// Attribute OriginHttpPort: The port of the origin station accessed when the HTTP protocol is used to return to the origin.
	AttrOriginHttpPort() interface{}
	// Attribute OriginHttpsPort: The port of the origin station accessed when the HTTPS protocol is used to return to the origin.
	AttrOriginHttpsPort() interface{}
	// Attribute OriginMtls: The mtls switch.
	AttrOriginMtls() interface{}
	// Attribute OriginReadTimeout: Read timeout interval of the source station (s).
	AttrOriginReadTimeout() interface{}
	// Attribute OriginScheme: The protocol used by the back-to-origin request.
	AttrOriginScheme() interface{}
	// Attribute OriginSni: SNI carried in the back-to-origin request.
	AttrOriginSni() interface{}
	// Attribute OriginVerify: Source station certificate verification switch.
	AttrOriginVerify() interface{}
	// Attribute Range: Use the range sharding method to download the file from the source.
	AttrRange() interface{}
	// Attribute RangeChunkSize: range shard size.
	AttrRangeChunkSize() interface{}
	// Attribute Rule: Rule content, using conditional expressions to match user requests.
	//
	// When adding global configuration, this parameter does not need to be set.
	AttrRule() interface{}
	// Attribute RuleEnable: Rule switch.
	//
	// When adding global configuration, this parameter does not need to be set.
	AttrRuleEnable() interface{}
	// Attribute RuleName: Rule name.
	//
	// When adding global configuration, this parameter does not need to be set.
	AttrRuleName() interface{}
	// Attribute Sequence: Order of rule execution.
	//
	// The smaller the value, the higher the priority for execution.
	AttrSequence() interface{}
	// Attribute SiteVersion: The version number of the site configuration.
	//
	// For sites that have enabled configuration version management, this parameter can be used to specify the effective version of the configuration site, which defaults to version 0.
	AttrSiteVersion() interface{}
	EnableResourcePropertyConstraint() *bool
	SetEnableResourcePropertyConstraint(val *bool)
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() alicloudroscdkcore.IResourceEnvironment
	Id() *string
	SetId(val *string)
	// The construct tree node associated with this construct.
	Node() alicloudroscdkcore.ConstructNode
	// Returns a string-encoded token that resolves to the physical name that should be passed to the ROS resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by ROS
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	Props() *OriginRuleProps
	Ref() *string
	Resource() alicloudroscdkcore.RosResource
	SetResource(val alicloudroscdkcore.RosResource)
	Scope() alicloudroscdkcore.Construct
	SetScope(val alicloudroscdkcore.Construct)
	// The stack in which this resource is defined.
	Stack() alicloudroscdkcore.Stack
	AddCondition(condition alicloudroscdkcore.RosCondition)
	AddCount(count interface{})
	AddDependency(resource alicloudroscdkcore.Resource)
	AddResourceDesc(desc *string)
	ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy)
	FetchCondition() alicloudroscdkcore.RosCondition
	FetchDependency() *[]*string
	FetchResourceDesc() *string
	GeneratePhysicalName() *string
	GetAtt(name *string) alicloudroscdkcore.IResolvable
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	OnValidate() *[]*string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	Prepare()
	SetMetadata(key *string, value interface{})
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	Synthesize(session alicloudroscdkcore.ISynthesisSession)
	// Returns a string representation of this construct.
	ToString() *string
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	Validate() *[]*string
}

// The jsii proxy struct for OriginRule
type jsiiProxy_OriginRule struct {
	internal.Type__alicloudroscdkcoreResource
	jsiiProxy_IOriginRule
}

func (j *jsiiProxy_OriginRule) AttrConfigId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrConfigId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrConfigType() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrConfigType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrDnsRecord() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrDnsRecord",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrFollow302Enable() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrFollow302Enable",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrFollow302MaxTries() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrFollow302MaxTries",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrFollow302RetainArgs() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrFollow302RetainArgs",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrFollow302RetainHeader() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrFollow302RetainHeader",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrFollow302TargetHost() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrFollow302TargetHost",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrOriginHost() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrOriginHost",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrOriginHttpPort() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrOriginHttpPort",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrOriginHttpsPort() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrOriginHttpsPort",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrOriginMtls() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrOriginMtls",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrOriginReadTimeout() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrOriginReadTimeout",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrOriginScheme() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrOriginScheme",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrOriginSni() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrOriginSni",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrOriginVerify() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrOriginVerify",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrRange() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrRange",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrRangeChunkSize() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrRangeChunkSize",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrRule() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrRule",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrRuleEnable() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrRuleEnable",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrRuleName() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrRuleName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrSequence() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrSequence",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) AttrSiteVersion() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrSiteVersion",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) EnableResourcePropertyConstraint() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"enableResourcePropertyConstraint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) Env() alicloudroscdkcore.IResourceEnvironment {
	var returns alicloudroscdkcore.IResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) Id() *string {
	var returns *string
	_jsii_.Get(
		j,
		"id",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) Node() alicloudroscdkcore.ConstructNode {
	var returns alicloudroscdkcore.ConstructNode
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) Props() *OriginRuleProps {
	var returns *OriginRuleProps
	_jsii_.Get(
		j,
		"props",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) Ref() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ref",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) Resource() alicloudroscdkcore.RosResource {
	var returns alicloudroscdkcore.RosResource
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) Scope() alicloudroscdkcore.Construct {
	var returns alicloudroscdkcore.Construct
	_jsii_.Get(
		j,
		"scope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_OriginRule) Stack() alicloudroscdkcore.Stack {
	var returns alicloudroscdkcore.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewOriginRule(scope alicloudroscdkcore.Construct, id *string, props *OriginRuleProps, enableResourcePropertyConstraint *bool) OriginRule {
	_init_.Initialize()

	if err := validateNewOriginRuleParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_OriginRule{}

	_jsii_.Create(
		"@alicloud/ros-cdk-esa.OriginRule",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		&j,
	)

	return &j
}

// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewOriginRule_Override(o OriginRule, scope alicloudroscdkcore.Construct, id *string, props *OriginRuleProps, enableResourcePropertyConstraint *bool) {
	_init_.Initialize()

	_jsii_.Create(
		"@alicloud/ros-cdk-esa.OriginRule",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		o,
	)
}

func (j *jsiiProxy_OriginRule)SetEnableResourcePropertyConstraint(val *bool) {
	if err := j.validateSetEnableResourcePropertyConstraintParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"enableResourcePropertyConstraint",
		val,
	)
}

func (j *jsiiProxy_OriginRule)SetId(val *string) {
	if err := j.validateSetIdParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"id",
		val,
	)
}

func (j *jsiiProxy_OriginRule)SetResource(val alicloudroscdkcore.RosResource) {
	_jsii_.Set(
		j,
		"resource",
		val,
	)
}

func (j *jsiiProxy_OriginRule)SetScope(val alicloudroscdkcore.Construct) {
	if err := j.validateSetScopeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"scope",
		val,
	)
}

// Return whether the given object is a Construct.
func OriginRule_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateOriginRule_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@alicloud/ros-cdk-esa.OriginRule",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func (o *jsiiProxy_OriginRule) AddCondition(condition alicloudroscdkcore.RosCondition) {
	if err := o.validateAddConditionParameters(condition); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		o,
		"addCondition",
		[]interface{}{condition},
	)
}

func (o *jsiiProxy_OriginRule) AddCount(count interface{}) {
	if err := o.validateAddCountParameters(count); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		o,
		"addCount",
		[]interface{}{count},
	)
}

func (o *jsiiProxy_OriginRule) AddDependency(resource alicloudroscdkcore.Resource) {
	if err := o.validateAddDependencyParameters(resource); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		o,
		"addDependency",
		[]interface{}{resource},
	)
}

func (o *jsiiProxy_OriginRule) AddResourceDesc(desc *string) {
	if err := o.validateAddResourceDescParameters(desc); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		o,
		"addResourceDesc",
		[]interface{}{desc},
	)
}

func (o *jsiiProxy_OriginRule) ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy) {
	if err := o.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		o,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (o *jsiiProxy_OriginRule) FetchCondition() alicloudroscdkcore.RosCondition {
	var returns alicloudroscdkcore.RosCondition

	_jsii_.Invoke(
		o,
		"fetchCondition",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (o *jsiiProxy_OriginRule) FetchDependency() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		o,
		"fetchDependency",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (o *jsiiProxy_OriginRule) FetchResourceDesc() *string {
	var returns *string

	_jsii_.Invoke(
		o,
		"fetchResourceDesc",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (o *jsiiProxy_OriginRule) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		o,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (o *jsiiProxy_OriginRule) GetAtt(name *string) alicloudroscdkcore.IResolvable {
	if err := o.validateGetAttParameters(name); err != nil {
		panic(err)
	}
	var returns alicloudroscdkcore.IResolvable

	_jsii_.Invoke(
		o,
		"getAtt",
		[]interface{}{name},
		&returns,
	)

	return returns
}

func (o *jsiiProxy_OriginRule) OnPrepare() {
	_jsii_.InvokeVoid(
		o,
		"onPrepare",
		nil, // no parameters
	)
}

func (o *jsiiProxy_OriginRule) OnSynthesize(session constructs.ISynthesisSession) {
	if err := o.validateOnSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		o,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (o *jsiiProxy_OriginRule) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		o,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (o *jsiiProxy_OriginRule) Prepare() {
	_jsii_.InvokeVoid(
		o,
		"prepare",
		nil, // no parameters
	)
}

func (o *jsiiProxy_OriginRule) SetMetadata(key *string, value interface{}) {
	if err := o.validateSetMetadataParameters(key, value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		o,
		"setMetadata",
		[]interface{}{key, value},
	)
}

func (o *jsiiProxy_OriginRule) Synthesize(session alicloudroscdkcore.ISynthesisSession) {
	if err := o.validateSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		o,
		"synthesize",
		[]interface{}{session},
	)
}

func (o *jsiiProxy_OriginRule) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		o,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (o *jsiiProxy_OriginRule) Validate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		o,
		"validate",
		nil, // no parameters
		&returns,
	)

	return returns
}

