package alicloudroscdkesa

import (
	_init_ "github.com/alibabacloud-go/ros-cdk/alicloudroscdkesa/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkcore"
	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkesa/internal"
	"github.com/aws/constructs-go/constructs/v3"
)

// This class encapsulates and extends the ROS resource type `ALIYUN::ESA::ScheduledPreloadJob`.
type ScheduledPreloadJob interface {
	alicloudroscdkcore.Resource
	IScheduledPreloadJob
	// Attribute CreateTime: The time when the task was created.
	AttrCreateTime() interface{}
	// Attribute Domains: The domain names to be prefetched.
	AttrDomains() interface{}
	// Attribute ErrorInfo: The error message.
	AttrErrorInfo() interface{}
	// Attribute FailedFileOss: OSS address of failed file.
	AttrFailedFileOss() interface{}
	// Attribute FileId: The ID of the URL list file, which can be used during downloads.
	AttrFileId() interface{}
	// Attribute InsertWay: The method to submit the URLs to be prefetched.
	AttrInsertWay() interface{}
	// Attribute ScheduledPreloadJobId: The ID of the prefetch task.
	AttrScheduledPreloadJobId() interface{}
	// Attribute ScheduledPreloadJobName: The task name.
	AttrScheduledPreloadJobName() interface{}
	// Attribute SiteId: The site ID.
	AttrSiteId() interface{}
	// Attribute TaskSubmitted: The number of submitted prefetch tasks.
	AttrTaskSubmitted() interface{}
	// Attribute TaskType: The task type.
	//
	// Valid values: refresh and preload.
	AttrTaskType() interface{}
	// Attribute UrlCount: The total number of URLs.
	AttrUrlCount() interface{}
	// Attribute UrlSubmitted: The number of submitted URLs.
	AttrUrlSubmitted() interface{}
	EnableResourcePropertyConstraint() *bool
	SetEnableResourcePropertyConstraint(val *bool)
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() alicloudroscdkcore.IResourceEnvironment
	Id() *string
	SetId(val *string)
	// The construct tree node associated with this construct.
	Node() alicloudroscdkcore.ConstructNode
	// Returns a string-encoded token that resolves to the physical name that should be passed to the ROS resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by ROS
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	Props() *ScheduledPreloadJobProps
	Ref() *string
	Resource() alicloudroscdkcore.RosResource
	SetResource(val alicloudroscdkcore.RosResource)
	Scope() alicloudroscdkcore.Construct
	SetScope(val alicloudroscdkcore.Construct)
	// The stack in which this resource is defined.
	Stack() alicloudroscdkcore.Stack
	AddCondition(condition alicloudroscdkcore.RosCondition)
	AddCount(count interface{})
	AddDependency(resource alicloudroscdkcore.Resource)
	AddResourceDesc(desc *string)
	ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy)
	FetchCondition() alicloudroscdkcore.RosCondition
	FetchDependency() *[]*string
	FetchResourceDesc() *string
	GeneratePhysicalName() *string
	GetAtt(name *string) alicloudroscdkcore.IResolvable
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	OnValidate() *[]*string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	Prepare()
	SetMetadata(key *string, value interface{})
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	Synthesize(session alicloudroscdkcore.ISynthesisSession)
	// Returns a string representation of this construct.
	ToString() *string
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	Validate() *[]*string
}

// The jsii proxy struct for ScheduledPreloadJob
type jsiiProxy_ScheduledPreloadJob struct {
	internal.Type__alicloudroscdkcoreResource
	jsiiProxy_IScheduledPreloadJob
}

func (j *jsiiProxy_ScheduledPreloadJob) AttrCreateTime() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrCreateTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) AttrDomains() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrDomains",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) AttrErrorInfo() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrErrorInfo",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) AttrFailedFileOss() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrFailedFileOss",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) AttrFileId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrFileId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) AttrInsertWay() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrInsertWay",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) AttrScheduledPreloadJobId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrScheduledPreloadJobId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) AttrScheduledPreloadJobName() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrScheduledPreloadJobName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) AttrSiteId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrSiteId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) AttrTaskSubmitted() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrTaskSubmitted",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) AttrTaskType() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrTaskType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) AttrUrlCount() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrUrlCount",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) AttrUrlSubmitted() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrUrlSubmitted",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) EnableResourcePropertyConstraint() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"enableResourcePropertyConstraint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) Env() alicloudroscdkcore.IResourceEnvironment {
	var returns alicloudroscdkcore.IResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) Id() *string {
	var returns *string
	_jsii_.Get(
		j,
		"id",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) Node() alicloudroscdkcore.ConstructNode {
	var returns alicloudroscdkcore.ConstructNode
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) Props() *ScheduledPreloadJobProps {
	var returns *ScheduledPreloadJobProps
	_jsii_.Get(
		j,
		"props",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) Ref() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ref",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) Resource() alicloudroscdkcore.RosResource {
	var returns alicloudroscdkcore.RosResource
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) Scope() alicloudroscdkcore.Construct {
	var returns alicloudroscdkcore.Construct
	_jsii_.Get(
		j,
		"scope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ScheduledPreloadJob) Stack() alicloudroscdkcore.Stack {
	var returns alicloudroscdkcore.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewScheduledPreloadJob(scope alicloudroscdkcore.Construct, id *string, props *ScheduledPreloadJobProps, enableResourcePropertyConstraint *bool) ScheduledPreloadJob {
	_init_.Initialize()

	if err := validateNewScheduledPreloadJobParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_ScheduledPreloadJob{}

	_jsii_.Create(
		"@alicloud/ros-cdk-esa.ScheduledPreloadJob",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		&j,
	)

	return &j
}

// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewScheduledPreloadJob_Override(s ScheduledPreloadJob, scope alicloudroscdkcore.Construct, id *string, props *ScheduledPreloadJobProps, enableResourcePropertyConstraint *bool) {
	_init_.Initialize()

	_jsii_.Create(
		"@alicloud/ros-cdk-esa.ScheduledPreloadJob",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		s,
	)
}

func (j *jsiiProxy_ScheduledPreloadJob)SetEnableResourcePropertyConstraint(val *bool) {
	if err := j.validateSetEnableResourcePropertyConstraintParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"enableResourcePropertyConstraint",
		val,
	)
}

func (j *jsiiProxy_ScheduledPreloadJob)SetId(val *string) {
	if err := j.validateSetIdParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"id",
		val,
	)
}

func (j *jsiiProxy_ScheduledPreloadJob)SetResource(val alicloudroscdkcore.RosResource) {
	_jsii_.Set(
		j,
		"resource",
		val,
	)
}

func (j *jsiiProxy_ScheduledPreloadJob)SetScope(val alicloudroscdkcore.Construct) {
	if err := j.validateSetScopeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"scope",
		val,
	)
}

// Return whether the given object is a Construct.
func ScheduledPreloadJob_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateScheduledPreloadJob_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@alicloud/ros-cdk-esa.ScheduledPreloadJob",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func (s *jsiiProxy_ScheduledPreloadJob) AddCondition(condition alicloudroscdkcore.RosCondition) {
	if err := s.validateAddConditionParameters(condition); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		s,
		"addCondition",
		[]interface{}{condition},
	)
}

func (s *jsiiProxy_ScheduledPreloadJob) AddCount(count interface{}) {
	if err := s.validateAddCountParameters(count); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		s,
		"addCount",
		[]interface{}{count},
	)
}

func (s *jsiiProxy_ScheduledPreloadJob) AddDependency(resource alicloudroscdkcore.Resource) {
	if err := s.validateAddDependencyParameters(resource); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		s,
		"addDependency",
		[]interface{}{resource},
	)
}

func (s *jsiiProxy_ScheduledPreloadJob) AddResourceDesc(desc *string) {
	if err := s.validateAddResourceDescParameters(desc); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		s,
		"addResourceDesc",
		[]interface{}{desc},
	)
}

func (s *jsiiProxy_ScheduledPreloadJob) ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy) {
	if err := s.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		s,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (s *jsiiProxy_ScheduledPreloadJob) FetchCondition() alicloudroscdkcore.RosCondition {
	var returns alicloudroscdkcore.RosCondition

	_jsii_.Invoke(
		s,
		"fetchCondition",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (s *jsiiProxy_ScheduledPreloadJob) FetchDependency() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		s,
		"fetchDependency",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (s *jsiiProxy_ScheduledPreloadJob) FetchResourceDesc() *string {
	var returns *string

	_jsii_.Invoke(
		s,
		"fetchResourceDesc",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (s *jsiiProxy_ScheduledPreloadJob) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		s,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (s *jsiiProxy_ScheduledPreloadJob) GetAtt(name *string) alicloudroscdkcore.IResolvable {
	if err := s.validateGetAttParameters(name); err != nil {
		panic(err)
	}
	var returns alicloudroscdkcore.IResolvable

	_jsii_.Invoke(
		s,
		"getAtt",
		[]interface{}{name},
		&returns,
	)

	return returns
}

func (s *jsiiProxy_ScheduledPreloadJob) OnPrepare() {
	_jsii_.InvokeVoid(
		s,
		"onPrepare",
		nil, // no parameters
	)
}

func (s *jsiiProxy_ScheduledPreloadJob) OnSynthesize(session constructs.ISynthesisSession) {
	if err := s.validateOnSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		s,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (s *jsiiProxy_ScheduledPreloadJob) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		s,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (s *jsiiProxy_ScheduledPreloadJob) Prepare() {
	_jsii_.InvokeVoid(
		s,
		"prepare",
		nil, // no parameters
	)
}

func (s *jsiiProxy_ScheduledPreloadJob) SetMetadata(key *string, value interface{}) {
	if err := s.validateSetMetadataParameters(key, value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		s,
		"setMetadata",
		[]interface{}{key, value},
	)
}

func (s *jsiiProxy_ScheduledPreloadJob) Synthesize(session alicloudroscdkcore.ISynthesisSession) {
	if err := s.validateSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		s,
		"synthesize",
		[]interface{}{session},
	)
}

func (s *jsiiProxy_ScheduledPreloadJob) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		s,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (s *jsiiProxy_ScheduledPreloadJob) Validate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		s,
		"validate",
		nil, // no parameters
		&returns,
	)

	return returns
}

