package alicloudroscdkesa

import (
	_init_ "github.com/alibabacloud-go/ros-cdk/alicloudroscdkesa/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkcore"
	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkesa/internal"
	"github.com/aws/constructs-go/constructs/v3"
)

// This class encapsulates and extends the ROS resource type `ALIYUN::ESA::WaitingRoom`.
type WaitingRoom interface {
	alicloudroscdkcore.Resource
	IWaitingRoom
	// Attribute CookieName: Custom Cookie name.
	AttrCookieName() interface{}
	// Attribute CustomPageHtml: User-defined waiting room page content, when the waiting room type is custom type, you need to enter.
	//
	// The incoming content needs to be base64 encoded.
	AttrCustomPageHtml() interface{}
	// Attribute Description: Waiting room description.
	AttrDescription() interface{}
	// Attribute DisableSessionRenewalEnable: Disable session renewal.
	AttrDisableSessionRenewalEnable() interface{}
	// Attribute HostNameAndPath: Host name and path.
	AttrHostNameAndPath() interface{}
	// Attribute JsonResponseEnable: The JSON response.
	//
	// If the accept request header contains "application/json", JSON data is returned.
	AttrJsonResponseEnable() interface{}
	// Attribute Language: The language of the waiting room page.
	//
	// When the waiting room type is the default type, it needs to be passed in.
	AttrLanguage() interface{}
	// Attribute NewUsersPerMinute: Number of new users per minute.
	AttrNewUsersPerMinute() interface{}
	// Attribute QueueAllEnable: All in line.
	AttrQueueAllEnable() interface{}
	// Attribute QueuingMethod: Way of queuing.
	AttrQueuingMethod() interface{}
	// Attribute QueuingStatusCode: Waiting room status code.
	AttrQueuingStatusCode() interface{}
	// Attribute SessionDuration: Session duration in minutes.
	AttrSessionDuration() interface{}
	// Attribute TotalActiveUsers: Total number of active users.
	AttrTotalActiveUsers() interface{}
	// Attribute WaitingRoomId: The waiting room ID.
	AttrWaitingRoomId() interface{}
	// Attribute WaitingRoomName: The name of the waiting room.
	AttrWaitingRoomName() interface{}
	// Attribute WaitingRoomType: Waiting room type, support:.
	AttrWaitingRoomType() interface{}
	EnableResourcePropertyConstraint() *bool
	SetEnableResourcePropertyConstraint(val *bool)
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() alicloudroscdkcore.IResourceEnvironment
	Id() *string
	SetId(val *string)
	// The construct tree node associated with this construct.
	Node() alicloudroscdkcore.ConstructNode
	// Returns a string-encoded token that resolves to the physical name that should be passed to the ROS resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by ROS
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	Props() *WaitingRoomProps
	Ref() *string
	Resource() alicloudroscdkcore.RosResource
	SetResource(val alicloudroscdkcore.RosResource)
	Scope() alicloudroscdkcore.Construct
	SetScope(val alicloudroscdkcore.Construct)
	// The stack in which this resource is defined.
	Stack() alicloudroscdkcore.Stack
	AddCondition(condition alicloudroscdkcore.RosCondition)
	AddCount(count interface{})
	AddDependency(resource alicloudroscdkcore.Resource)
	AddResourceDesc(desc *string)
	ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy)
	FetchCondition() alicloudroscdkcore.RosCondition
	FetchDependency() *[]*string
	FetchResourceDesc() *string
	GeneratePhysicalName() *string
	GetAtt(name *string) alicloudroscdkcore.IResolvable
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	OnValidate() *[]*string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	Prepare()
	SetMetadata(key *string, value interface{})
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	Synthesize(session alicloudroscdkcore.ISynthesisSession)
	// Returns a string representation of this construct.
	ToString() *string
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	Validate() *[]*string
}

// The jsii proxy struct for WaitingRoom
type jsiiProxy_WaitingRoom struct {
	internal.Type__alicloudroscdkcoreResource
	jsiiProxy_IWaitingRoom
}

func (j *jsiiProxy_WaitingRoom) AttrCookieName() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrCookieName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrCustomPageHtml() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrCustomPageHtml",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrDescription() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrDescription",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrDisableSessionRenewalEnable() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrDisableSessionRenewalEnable",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrHostNameAndPath() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrHostNameAndPath",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrJsonResponseEnable() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrJsonResponseEnable",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrLanguage() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrLanguage",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrNewUsersPerMinute() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrNewUsersPerMinute",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrQueueAllEnable() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrQueueAllEnable",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrQueuingMethod() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrQueuingMethod",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrQueuingStatusCode() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrQueuingStatusCode",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrSessionDuration() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrSessionDuration",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrTotalActiveUsers() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrTotalActiveUsers",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrWaitingRoomId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrWaitingRoomId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrWaitingRoomName() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrWaitingRoomName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) AttrWaitingRoomType() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrWaitingRoomType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) EnableResourcePropertyConstraint() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"enableResourcePropertyConstraint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) Env() alicloudroscdkcore.IResourceEnvironment {
	var returns alicloudroscdkcore.IResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) Id() *string {
	var returns *string
	_jsii_.Get(
		j,
		"id",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) Node() alicloudroscdkcore.ConstructNode {
	var returns alicloudroscdkcore.ConstructNode
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) Props() *WaitingRoomProps {
	var returns *WaitingRoomProps
	_jsii_.Get(
		j,
		"props",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) Ref() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ref",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) Resource() alicloudroscdkcore.RosResource {
	var returns alicloudroscdkcore.RosResource
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) Scope() alicloudroscdkcore.Construct {
	var returns alicloudroscdkcore.Construct
	_jsii_.Get(
		j,
		"scope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WaitingRoom) Stack() alicloudroscdkcore.Stack {
	var returns alicloudroscdkcore.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewWaitingRoom(scope alicloudroscdkcore.Construct, id *string, props *WaitingRoomProps, enableResourcePropertyConstraint *bool) WaitingRoom {
	_init_.Initialize()

	if err := validateNewWaitingRoomParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_WaitingRoom{}

	_jsii_.Create(
		"@alicloud/ros-cdk-esa.WaitingRoom",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		&j,
	)

	return &j
}

// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewWaitingRoom_Override(w WaitingRoom, scope alicloudroscdkcore.Construct, id *string, props *WaitingRoomProps, enableResourcePropertyConstraint *bool) {
	_init_.Initialize()

	_jsii_.Create(
		"@alicloud/ros-cdk-esa.WaitingRoom",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		w,
	)
}

func (j *jsiiProxy_WaitingRoom)SetEnableResourcePropertyConstraint(val *bool) {
	if err := j.validateSetEnableResourcePropertyConstraintParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"enableResourcePropertyConstraint",
		val,
	)
}

func (j *jsiiProxy_WaitingRoom)SetId(val *string) {
	if err := j.validateSetIdParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"id",
		val,
	)
}

func (j *jsiiProxy_WaitingRoom)SetResource(val alicloudroscdkcore.RosResource) {
	_jsii_.Set(
		j,
		"resource",
		val,
	)
}

func (j *jsiiProxy_WaitingRoom)SetScope(val alicloudroscdkcore.Construct) {
	if err := j.validateSetScopeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"scope",
		val,
	)
}

// Return whether the given object is a Construct.
func WaitingRoom_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateWaitingRoom_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@alicloud/ros-cdk-esa.WaitingRoom",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WaitingRoom) AddCondition(condition alicloudroscdkcore.RosCondition) {
	if err := w.validateAddConditionParameters(condition); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"addCondition",
		[]interface{}{condition},
	)
}

func (w *jsiiProxy_WaitingRoom) AddCount(count interface{}) {
	if err := w.validateAddCountParameters(count); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"addCount",
		[]interface{}{count},
	)
}

func (w *jsiiProxy_WaitingRoom) AddDependency(resource alicloudroscdkcore.Resource) {
	if err := w.validateAddDependencyParameters(resource); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"addDependency",
		[]interface{}{resource},
	)
}

func (w *jsiiProxy_WaitingRoom) AddResourceDesc(desc *string) {
	if err := w.validateAddResourceDescParameters(desc); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"addResourceDesc",
		[]interface{}{desc},
	)
}

func (w *jsiiProxy_WaitingRoom) ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy) {
	if err := w.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (w *jsiiProxy_WaitingRoom) FetchCondition() alicloudroscdkcore.RosCondition {
	var returns alicloudroscdkcore.RosCondition

	_jsii_.Invoke(
		w,
		"fetchCondition",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WaitingRoom) FetchDependency() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		w,
		"fetchDependency",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WaitingRoom) FetchResourceDesc() *string {
	var returns *string

	_jsii_.Invoke(
		w,
		"fetchResourceDesc",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WaitingRoom) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		w,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WaitingRoom) GetAtt(name *string) alicloudroscdkcore.IResolvable {
	if err := w.validateGetAttParameters(name); err != nil {
		panic(err)
	}
	var returns alicloudroscdkcore.IResolvable

	_jsii_.Invoke(
		w,
		"getAtt",
		[]interface{}{name},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WaitingRoom) OnPrepare() {
	_jsii_.InvokeVoid(
		w,
		"onPrepare",
		nil, // no parameters
	)
}

func (w *jsiiProxy_WaitingRoom) OnSynthesize(session constructs.ISynthesisSession) {
	if err := w.validateOnSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (w *jsiiProxy_WaitingRoom) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		w,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WaitingRoom) Prepare() {
	_jsii_.InvokeVoid(
		w,
		"prepare",
		nil, // no parameters
	)
}

func (w *jsiiProxy_WaitingRoom) SetMetadata(key *string, value interface{}) {
	if err := w.validateSetMetadataParameters(key, value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"setMetadata",
		[]interface{}{key, value},
	)
}

func (w *jsiiProxy_WaitingRoom) Synthesize(session alicloudroscdkcore.ISynthesisSession) {
	if err := w.validateSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"synthesize",
		[]interface{}{session},
	)
}

func (w *jsiiProxy_WaitingRoom) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		w,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WaitingRoom) Validate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		w,
		"validate",
		nil, // no parameters
		&returns,
	)

	return returns
}

