package com.aliyun.ros.cdk.pai.datasource;

/**
 * Properties for defining a <code>DATASOURCE::PAI::Datasets</code>.
 */
@javax.annotation.Generated(value = "jsii-pacmak/1.85.0 (build 08ee592)", date = "2023-09-25T10:01:46.919Z")
@software.amazon.jsii.Jsii(module = com.aliyun.ros.cdk.pai.$Module.class, fqn = "@alicloud/ros-cdk-pai.datasource.DatasetsProps")
@software.amazon.jsii.Jsii.Proxy(DatasetsProps.Jsii$Proxy.class)
public interface DatasetsProps extends software.amazon.jsii.JsiiSerializable {

    /**
     * Property workspaceId: The ID of the workspace where the dataset is located.
     * <p>
     * For details about how to obtain the workspace ID, see [ListWorkspaces](~~ 449124 ~~).
     * If this parameter is not configured, the default workspace is used. If the default workspace does not exist, an error is reported.
     */
    @org.jetbrains.annotations.NotNull java.lang.Object getWorkspaceId();

    /**
     * Property sourceId: The data source ID.
     * <p>
     * <ul>
     * <li>When the SourceType is USER, SourceId can be customized.</li>
     * <li>When SourceType is ITAG, that is, when the iTAG module labels the data set generated by the result, SourceId is the task ID of ITAG.</li>
     * <li>When SourceType is PAI_PUBLIC_DATASET, that is, a dataset created using PAI public datasets, SourceId is empty by default.</li>
     * </ul>
     */
    default @org.jetbrains.annotations.Nullable java.lang.Object getSourceId() {
        return null;
    }

    /**
     * @return a {@link Builder} of {@link DatasetsProps}
     */
    static Builder builder() {
        return new Builder();
    }
    /**
     * A builder for {@link DatasetsProps}
     */
    public static final class Builder implements software.amazon.jsii.Builder<DatasetsProps> {
        java.lang.Object workspaceId;
        java.lang.Object sourceId;

        /**
         * Sets the value of {@link DatasetsProps#getWorkspaceId}
         * @param workspaceId Property workspaceId: The ID of the workspace where the dataset is located. This parameter is required.
         *                    For details about how to obtain the workspace ID, see [ListWorkspaces](~~ 449124 ~~).
         *                    If this parameter is not configured, the default workspace is used. If the default workspace does not exist, an error is reported.
         * @return {@code this}
         */
        public Builder workspaceId(java.lang.String workspaceId) {
            this.workspaceId = workspaceId;
            return this;
        }

        /**
         * Sets the value of {@link DatasetsProps#getWorkspaceId}
         * @param workspaceId Property workspaceId: The ID of the workspace where the dataset is located. This parameter is required.
         *                    For details about how to obtain the workspace ID, see [ListWorkspaces](~~ 449124 ~~).
         *                    If this parameter is not configured, the default workspace is used. If the default workspace does not exist, an error is reported.
         * @return {@code this}
         */
        public Builder workspaceId(com.aliyun.ros.cdk.core.IResolvable workspaceId) {
            this.workspaceId = workspaceId;
            return this;
        }

        /**
         * Sets the value of {@link DatasetsProps#getSourceId}
         * @param sourceId Property sourceId: The data source ID.
         *                 <ul>
         *                 <li>When the SourceType is USER, SourceId can be customized.</li>
         *                 <li>When SourceType is ITAG, that is, when the iTAG module labels the data set generated by the result, SourceId is the task ID of ITAG.</li>
         *                 <li>When SourceType is PAI_PUBLIC_DATASET, that is, a dataset created using PAI public datasets, SourceId is empty by default.</li>
         *                 </ul>
         * @return {@code this}
         */
        public Builder sourceId(java.lang.String sourceId) {
            this.sourceId = sourceId;
            return this;
        }

        /**
         * Sets the value of {@link DatasetsProps#getSourceId}
         * @param sourceId Property sourceId: The data source ID.
         *                 <ul>
         *                 <li>When the SourceType is USER, SourceId can be customized.</li>
         *                 <li>When SourceType is ITAG, that is, when the iTAG module labels the data set generated by the result, SourceId is the task ID of ITAG.</li>
         *                 <li>When SourceType is PAI_PUBLIC_DATASET, that is, a dataset created using PAI public datasets, SourceId is empty by default.</li>
         *                 </ul>
         * @return {@code this}
         */
        public Builder sourceId(com.aliyun.ros.cdk.core.IResolvable sourceId) {
            this.sourceId = sourceId;
            return this;
        }

        /**
         * Builds the configured instance.
         * @return a new instance of {@link DatasetsProps}
         * @throws NullPointerException if any required attribute was not provided
         */
        @Override
        public DatasetsProps build() {
            return new Jsii$Proxy(this);
        }
    }

    /**
     * An implementation for {@link DatasetsProps}
     */
    @software.amazon.jsii.Internal
    final class Jsii$Proxy extends software.amazon.jsii.JsiiObject implements DatasetsProps {
        private final java.lang.Object workspaceId;
        private final java.lang.Object sourceId;

        /**
         * Constructor that initializes the object based on values retrieved from the JsiiObject.
         * @param objRef Reference to the JSII managed object.
         */
        protected Jsii$Proxy(final software.amazon.jsii.JsiiObjectRef objRef) {
            super(objRef);
            this.workspaceId = software.amazon.jsii.Kernel.get(this, "workspaceId", software.amazon.jsii.NativeType.forClass(java.lang.Object.class));
            this.sourceId = software.amazon.jsii.Kernel.get(this, "sourceId", software.amazon.jsii.NativeType.forClass(java.lang.Object.class));
        }

        /**
         * Constructor that initializes the object based on literal property values passed by the {@link Builder}.
         */
        protected Jsii$Proxy(final Builder builder) {
            super(software.amazon.jsii.JsiiObject.InitializationMode.JSII);
            this.workspaceId = java.util.Objects.requireNonNull(builder.workspaceId, "workspaceId is required");
            this.sourceId = builder.sourceId;
        }

        @Override
        public final java.lang.Object getWorkspaceId() {
            return this.workspaceId;
        }

        @Override
        public final java.lang.Object getSourceId() {
            return this.sourceId;
        }

        @Override
        @software.amazon.jsii.Internal
        public com.fasterxml.jackson.databind.JsonNode $jsii$toJson() {
            final com.fasterxml.jackson.databind.ObjectMapper om = software.amazon.jsii.JsiiObjectMapper.INSTANCE;
            final com.fasterxml.jackson.databind.node.ObjectNode data = com.fasterxml.jackson.databind.node.JsonNodeFactory.instance.objectNode();

            data.set("workspaceId", om.valueToTree(this.getWorkspaceId()));
            if (this.getSourceId() != null) {
                data.set("sourceId", om.valueToTree(this.getSourceId()));
            }

            final com.fasterxml.jackson.databind.node.ObjectNode struct = com.fasterxml.jackson.databind.node.JsonNodeFactory.instance.objectNode();
            struct.set("fqn", om.valueToTree("@alicloud/ros-cdk-pai.datasource.DatasetsProps"));
            struct.set("data", data);

            final com.fasterxml.jackson.databind.node.ObjectNode obj = com.fasterxml.jackson.databind.node.JsonNodeFactory.instance.objectNode();
            obj.set("$jsii.struct", struct);

            return obj;
        }

        @Override
        public final boolean equals(final Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            DatasetsProps.Jsii$Proxy that = (DatasetsProps.Jsii$Proxy) o;

            if (!workspaceId.equals(that.workspaceId)) return false;
            return this.sourceId != null ? this.sourceId.equals(that.sourceId) : that.sourceId == null;
        }

        @Override
        public final int hashCode() {
            int result = this.workspaceId.hashCode();
            result = 31 * result + (this.sourceId != null ? this.sourceId.hashCode() : 0);
            return result;
        }
    }
}
