package alicloudroscdkcr

import (
	_init_ "github.com/alibabacloud-go/ros-cdk/alicloudroscdkcr/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkcore"
	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkcr/internal"
	"github.com/aws/constructs-go/constructs/v3"
)

// This class encapsulates and extends the ROS resource type `ALIYUN::CR::ArtifactLifecycleRule`.
type ArtifactLifecycleRule interface {
	alicloudroscdkcore.Resource
	IArtifactLifecycleRule
	// Attribute ArtifactLifecycleRuleId: The ID of the lifecycle management rule.
	AttrArtifactLifecycleRuleId() interface{}
	// Attribute Auto: Specify whether to automatically execute the lifecycle management rule.
	AttrAuto() interface{}
	// Attribute CreateTime: Creation time of the lifecycle management rule.
	AttrCreateTime() interface{}
	// Attribute InstanceId: ACR Instance ID.
	AttrInstanceId() interface{}
	// Attribute ModifiedTime: Change time of the lifecycle management rule.
	AttrModifiedTime() interface{}
	// Attribute NamespaceName: The name of the namespace.
	AttrNamespaceName() interface{}
	// Attribute RepoName: The name of the image repository.
	AttrRepoName() interface{}
	// Attribute RetentionTagCount: The number of images that you want to retain.
	AttrRetentionTagCount() interface{}
	// Attribute ScheduleTime: The execution cycle of the lifecycle management rule.
	AttrScheduleTime() interface{}
	// Attribute Scope: The deletion scope.
	AttrScope() interface{}
	// Attribute TagRegexp: The regular expression that is used to indicate which image tags are retained.
	AttrTagRegexp() interface{}
	EnableResourcePropertyConstraint() *bool
	SetEnableResourcePropertyConstraint(val *bool)
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() alicloudroscdkcore.IResourceEnvironment
	Id() *string
	SetId(val *string)
	// The construct tree node associated with this construct.
	Node() alicloudroscdkcore.ConstructNode
	// Returns a string-encoded token that resolves to the physical name that should be passed to the ROS resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by ROS
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	Props() *ArtifactLifecycleRuleProps
	Ref() *string
	Resource() alicloudroscdkcore.RosResource
	SetResource(val alicloudroscdkcore.RosResource)
	Scope() alicloudroscdkcore.Construct
	SetScope(val alicloudroscdkcore.Construct)
	// The stack in which this resource is defined.
	Stack() alicloudroscdkcore.Stack
	AddCondition(condition alicloudroscdkcore.RosCondition)
	AddCount(count interface{})
	AddDependency(resource alicloudroscdkcore.Resource)
	AddResourceDesc(desc *string)
	ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy)
	FetchCondition() alicloudroscdkcore.RosCondition
	FetchDependency() *[]*string
	FetchResourceDesc() *string
	GeneratePhysicalName() *string
	GetAtt(name *string) alicloudroscdkcore.IResolvable
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	OnValidate() *[]*string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	Prepare()
	SetMetadata(key *string, value interface{})
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	Synthesize(session alicloudroscdkcore.ISynthesisSession)
	// Returns a string representation of this construct.
	ToString() *string
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	Validate() *[]*string
}

// The jsii proxy struct for ArtifactLifecycleRule
type jsiiProxy_ArtifactLifecycleRule struct {
	internal.Type__alicloudroscdkcoreResource
	jsiiProxy_IArtifactLifecycleRule
}

func (j *jsiiProxy_ArtifactLifecycleRule) AttrArtifactLifecycleRuleId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrArtifactLifecycleRuleId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) AttrAuto() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrAuto",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) AttrCreateTime() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrCreateTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) AttrInstanceId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrInstanceId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) AttrModifiedTime() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrModifiedTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) AttrNamespaceName() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrNamespaceName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) AttrRepoName() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrRepoName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) AttrRetentionTagCount() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrRetentionTagCount",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) AttrScheduleTime() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrScheduleTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) AttrScope() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrScope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) AttrTagRegexp() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrTagRegexp",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) EnableResourcePropertyConstraint() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"enableResourcePropertyConstraint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) Env() alicloudroscdkcore.IResourceEnvironment {
	var returns alicloudroscdkcore.IResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) Id() *string {
	var returns *string
	_jsii_.Get(
		j,
		"id",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) Node() alicloudroscdkcore.ConstructNode {
	var returns alicloudroscdkcore.ConstructNode
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) Props() *ArtifactLifecycleRuleProps {
	var returns *ArtifactLifecycleRuleProps
	_jsii_.Get(
		j,
		"props",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) Ref() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ref",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) Resource() alicloudroscdkcore.RosResource {
	var returns alicloudroscdkcore.RosResource
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) Scope() alicloudroscdkcore.Construct {
	var returns alicloudroscdkcore.Construct
	_jsii_.Get(
		j,
		"scope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ArtifactLifecycleRule) Stack() alicloudroscdkcore.Stack {
	var returns alicloudroscdkcore.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewArtifactLifecycleRule(scope alicloudroscdkcore.Construct, id *string, props *ArtifactLifecycleRuleProps, enableResourcePropertyConstraint *bool) ArtifactLifecycleRule {
	_init_.Initialize()

	if err := validateNewArtifactLifecycleRuleParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_ArtifactLifecycleRule{}

	_jsii_.Create(
		"@alicloud/ros-cdk-cr.ArtifactLifecycleRule",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		&j,
	)

	return &j
}

// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewArtifactLifecycleRule_Override(a ArtifactLifecycleRule, scope alicloudroscdkcore.Construct, id *string, props *ArtifactLifecycleRuleProps, enableResourcePropertyConstraint *bool) {
	_init_.Initialize()

	_jsii_.Create(
		"@alicloud/ros-cdk-cr.ArtifactLifecycleRule",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		a,
	)
}

func (j *jsiiProxy_ArtifactLifecycleRule)SetEnableResourcePropertyConstraint(val *bool) {
	if err := j.validateSetEnableResourcePropertyConstraintParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"enableResourcePropertyConstraint",
		val,
	)
}

func (j *jsiiProxy_ArtifactLifecycleRule)SetId(val *string) {
	if err := j.validateSetIdParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"id",
		val,
	)
}

func (j *jsiiProxy_ArtifactLifecycleRule)SetResource(val alicloudroscdkcore.RosResource) {
	_jsii_.Set(
		j,
		"resource",
		val,
	)
}

func (j *jsiiProxy_ArtifactLifecycleRule)SetScope(val alicloudroscdkcore.Construct) {
	if err := j.validateSetScopeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"scope",
		val,
	)
}

// Return whether the given object is a Construct.
func ArtifactLifecycleRule_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateArtifactLifecycleRule_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@alicloud/ros-cdk-cr.ArtifactLifecycleRule",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ArtifactLifecycleRule) AddCondition(condition alicloudroscdkcore.RosCondition) {
	if err := a.validateAddConditionParameters(condition); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		a,
		"addCondition",
		[]interface{}{condition},
	)
}

func (a *jsiiProxy_ArtifactLifecycleRule) AddCount(count interface{}) {
	if err := a.validateAddCountParameters(count); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		a,
		"addCount",
		[]interface{}{count},
	)
}

func (a *jsiiProxy_ArtifactLifecycleRule) AddDependency(resource alicloudroscdkcore.Resource) {
	if err := a.validateAddDependencyParameters(resource); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		a,
		"addDependency",
		[]interface{}{resource},
	)
}

func (a *jsiiProxy_ArtifactLifecycleRule) AddResourceDesc(desc *string) {
	if err := a.validateAddResourceDescParameters(desc); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		a,
		"addResourceDesc",
		[]interface{}{desc},
	)
}

func (a *jsiiProxy_ArtifactLifecycleRule) ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy) {
	if err := a.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		a,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (a *jsiiProxy_ArtifactLifecycleRule) FetchCondition() alicloudroscdkcore.RosCondition {
	var returns alicloudroscdkcore.RosCondition

	_jsii_.Invoke(
		a,
		"fetchCondition",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ArtifactLifecycleRule) FetchDependency() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		a,
		"fetchDependency",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ArtifactLifecycleRule) FetchResourceDesc() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"fetchResourceDesc",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ArtifactLifecycleRule) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ArtifactLifecycleRule) GetAtt(name *string) alicloudroscdkcore.IResolvable {
	if err := a.validateGetAttParameters(name); err != nil {
		panic(err)
	}
	var returns alicloudroscdkcore.IResolvable

	_jsii_.Invoke(
		a,
		"getAtt",
		[]interface{}{name},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ArtifactLifecycleRule) OnPrepare() {
	_jsii_.InvokeVoid(
		a,
		"onPrepare",
		nil, // no parameters
	)
}

func (a *jsiiProxy_ArtifactLifecycleRule) OnSynthesize(session constructs.ISynthesisSession) {
	if err := a.validateOnSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		a,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (a *jsiiProxy_ArtifactLifecycleRule) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		a,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ArtifactLifecycleRule) Prepare() {
	_jsii_.InvokeVoid(
		a,
		"prepare",
		nil, // no parameters
	)
}

func (a *jsiiProxy_ArtifactLifecycleRule) SetMetadata(key *string, value interface{}) {
	if err := a.validateSetMetadataParameters(key, value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		a,
		"setMetadata",
		[]interface{}{key, value},
	)
}

func (a *jsiiProxy_ArtifactLifecycleRule) Synthesize(session alicloudroscdkcore.ISynthesisSession) {
	if err := a.validateSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		a,
		"synthesize",
		[]interface{}{session},
	)
}

func (a *jsiiProxy_ArtifactLifecycleRule) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ArtifactLifecycleRule) Validate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		a,
		"validate",
		nil, // no parameters
		&returns,
	)

	return returns
}

