package datasource


// Properties for defining a `Datasets`.
//
// See https://www.alibabacloud.com/help/ros/developer-reference/datasource-pai-datasets
type DatasetsProps struct {
	// Property workspaceId: The ID of the workspace where the dataset is located.
	//
	// For details about how to obtain the workspace ID, see [ListWorkspaces](~~ 449124 ~~).
	// If this parameter is not configured, the default workspace is used. If the default workspace does not exist, an error is reported.
	WorkspaceId interface{} `field:"required" json:"workspaceId" yaml:"workspaceId"`
	// Property refreshOptions: The refresh strategy for the datasource resource when the stack is updated.
	//
	// Valid values:
	// - Never: Never refresh the datasource resource when the stack is updated.
	// - Always: Always refresh the datasource resource when the stack is updated.
	// Default is Never.
	RefreshOptions interface{} `field:"optional" json:"refreshOptions" yaml:"refreshOptions"`
	// Property sourceId: The data source ID.
	//
	// - When the SourceType is USER, SourceId can be customized.
	// - When SourceType is ITAG, that is, when the iTAG module labels the data set generated by the result, SourceId is the task ID of ITAG.
	// - When SourceType is PAI_PUBLIC_DATASET, that is, a dataset created using PAI public datasets, SourceId is empty by default.
	SourceId interface{} `field:"optional" json:"sourceId" yaml:"sourceId"`
}

