using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace AlibabaCloud.SDK.ROS.CDK.Cloudsso
{
    /// <summary>Properties for defining a `RosDirectory`.</summary>
    /// <remarks>
    /// See https://www.alibabacloud.com/help/ros/developer-reference/aliyun-cloudsso-directory
    /// </remarks>
    [JsiiInterface(nativeType: typeof(IRosDirectoryProps), fullyQualifiedName: "@alicloud/ros-cdk-cloudsso.RosDirectoryProps")]
    public interface IRosDirectoryProps
    {
        /// <remarks>
        /// <strong>Property</strong>: directoryName: The name of the directory. The name must be globally unique.
        /// The name can contain lowercase letters, digits, or hyphens (-). The name cannot start or end with a hyphen (-) and cannot contain two consecutive hyphens (-). The name cannot start with d-.
        /// The name must be 2 to 64 characters in length.
        /// **Note**: If you do not specify this parameter, the value of this parameter is automatically generated by the system.
        /// </remarks>
        [JsiiProperty(name: "directoryName", typeJson: "{\"union\":{\"types\":[{\"primitive\":\"string\"},{\"fqn\":\"@alicloud/ros-cdk-core.IResolvable\"}]}}", isOptional: true)]
        [Amazon.JSII.Runtime.Deputy.JsiiOptional]
        object? DirectoryName
        {
            get
            {
                return null;
            }
        }

        /// <summary>Properties for defining a `RosDirectory`.</summary>
        /// <remarks>
        /// See https://www.alibabacloud.com/help/ros/developer-reference/aliyun-cloudsso-directory
        /// </remarks>
        [JsiiTypeProxy(nativeType: typeof(IRosDirectoryProps), fullyQualifiedName: "@alicloud/ros-cdk-cloudsso.RosDirectoryProps")]
        internal sealed class _Proxy : DeputyBase, AlibabaCloud.SDK.ROS.CDK.Cloudsso.IRosDirectoryProps
        {
            private _Proxy(ByRefValue reference): base(reference)
            {
            }

            /// <remarks>
            /// <strong>Property</strong>: directoryName: The name of the directory. The name must be globally unique.
            /// The name can contain lowercase letters, digits, or hyphens (-). The name cannot start or end with a hyphen (-) and cannot contain two consecutive hyphens (-). The name cannot start with d-.
            /// The name must be 2 to 64 characters in length.
            /// **Note**: If you do not specify this parameter, the value of this parameter is automatically generated by the system.
            /// </remarks>
            [JsiiOptional]
            [JsiiProperty(name: "directoryName", typeJson: "{\"union\":{\"types\":[{\"primitive\":\"string\"},{\"fqn\":\"@alicloud/ros-cdk-core.IResolvable\"}]}}", isOptional: true)]
            public object? DirectoryName
            {
                get => GetInstanceProperty<object?>();
            }
        }
    }
}
