package alicloudroscdkgpdb

import (
	_init_ "github.com/alibabacloud-go/ros-cdk/alicloudroscdkgpdb/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkcore"
	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkgpdb/internal"
	"github.com/aws/constructs-go/constructs/v3"
)

// This class encapsulates and extends the ROS resource type `ALIYUN::GPDB::JdbcDataSource`.
type JdbcDataSource interface {
	alicloudroscdkcore.Resource
	IJdbcDataSource
	// Attribute ConnectionMessage: Return Information: If the connection fails, an error message is returned.
	//
	// Otherwise, "" is returned "".
	AttrConnectionMessage() interface{}
	// Attribute ConnectionStatus: Service Status:.
	AttrConnectionStatus() interface{}
	// Attribute CreateTime: The creation time of the resource.
	AttrCreateTime() interface{}
	// Attribute DataSourceDescription: Data Source Description.
	AttrDataSourceDescription() interface{}
	// Attribute DataSourceId: The data source ID.
	AttrDataSourceId() interface{}
	// Attribute DataSourceName: Data Source Name.
	AttrDataSourceName() interface{}
	// Attribute DataSourceType: Data Source Type.
	AttrDataSourceType() interface{}
	// Attribute ExternalDataServiceId: External Data Service id.
	AttrExternalDataServiceId() interface{}
	// Attribute JdbcConnectionString: The JDBC connection string.
	AttrJdbcConnectionString() interface{}
	// Attribute JdbcPassword: The password of the database account.
	AttrJdbcPassword() interface{}
	// Attribute JdbcUserName: The name of the database account.
	AttrJdbcUserName() interface{}
	// Attribute ModifyTime: Last modification time.
	AttrModifyTime() interface{}
	// Attribute StatusMessage: Service status information, such as exceptions, displays the reason for the exception.
	//
	// A null value in the normal Running state.
	AttrStatusMessage() interface{}
	EnableResourcePropertyConstraint() *bool
	SetEnableResourcePropertyConstraint(val *bool)
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() alicloudroscdkcore.IResourceEnvironment
	Id() *string
	SetId(val *string)
	// The construct tree node associated with this construct.
	Node() alicloudroscdkcore.ConstructNode
	// Returns a string-encoded token that resolves to the physical name that should be passed to the ROS resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by ROS
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	Props() *JdbcDataSourceProps
	Ref() *string
	Resource() alicloudroscdkcore.RosResource
	SetResource(val alicloudroscdkcore.RosResource)
	Scope() alicloudroscdkcore.Construct
	SetScope(val alicloudroscdkcore.Construct)
	// The stack in which this resource is defined.
	Stack() alicloudroscdkcore.Stack
	AddCondition(condition alicloudroscdkcore.RosCondition)
	AddCount(count interface{})
	AddDependency(resource alicloudroscdkcore.Resource)
	AddResourceDesc(desc *string)
	ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy)
	FetchCondition() alicloudroscdkcore.RosCondition
	FetchDependency() *[]*string
	FetchResourceDesc() *string
	GeneratePhysicalName() *string
	GetAtt(name *string) alicloudroscdkcore.IResolvable
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	OnValidate() *[]*string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	Prepare()
	SetMetadata(key *string, value interface{})
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	Synthesize(session alicloudroscdkcore.ISynthesisSession)
	// Returns a string representation of this construct.
	ToString() *string
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	Validate() *[]*string
}

// The jsii proxy struct for JdbcDataSource
type jsiiProxy_JdbcDataSource struct {
	internal.Type__alicloudroscdkcoreResource
	jsiiProxy_IJdbcDataSource
}

func (j *jsiiProxy_JdbcDataSource) AttrConnectionMessage() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrConnectionMessage",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) AttrConnectionStatus() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrConnectionStatus",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) AttrCreateTime() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrCreateTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) AttrDataSourceDescription() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrDataSourceDescription",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) AttrDataSourceId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrDataSourceId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) AttrDataSourceName() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrDataSourceName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) AttrDataSourceType() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrDataSourceType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) AttrExternalDataServiceId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrExternalDataServiceId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) AttrJdbcConnectionString() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrJdbcConnectionString",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) AttrJdbcPassword() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrJdbcPassword",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) AttrJdbcUserName() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrJdbcUserName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) AttrModifyTime() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrModifyTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) AttrStatusMessage() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrStatusMessage",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) EnableResourcePropertyConstraint() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"enableResourcePropertyConstraint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) Env() alicloudroscdkcore.IResourceEnvironment {
	var returns alicloudroscdkcore.IResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) Id() *string {
	var returns *string
	_jsii_.Get(
		j,
		"id",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) Node() alicloudroscdkcore.ConstructNode {
	var returns alicloudroscdkcore.ConstructNode
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) Props() *JdbcDataSourceProps {
	var returns *JdbcDataSourceProps
	_jsii_.Get(
		j,
		"props",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) Ref() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ref",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) Resource() alicloudroscdkcore.RosResource {
	var returns alicloudroscdkcore.RosResource
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) Scope() alicloudroscdkcore.Construct {
	var returns alicloudroscdkcore.Construct
	_jsii_.Get(
		j,
		"scope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_JdbcDataSource) Stack() alicloudroscdkcore.Stack {
	var returns alicloudroscdkcore.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewJdbcDataSource(scope alicloudroscdkcore.Construct, id *string, props *JdbcDataSourceProps, enableResourcePropertyConstraint *bool) JdbcDataSource {
	_init_.Initialize()

	if err := validateNewJdbcDataSourceParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_JdbcDataSource{}

	_jsii_.Create(
		"@alicloud/ros-cdk-gpdb.JdbcDataSource",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		&j,
	)

	return &j
}

// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewJdbcDataSource_Override(j JdbcDataSource, scope alicloudroscdkcore.Construct, id *string, props *JdbcDataSourceProps, enableResourcePropertyConstraint *bool) {
	_init_.Initialize()

	_jsii_.Create(
		"@alicloud/ros-cdk-gpdb.JdbcDataSource",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		j,
	)
}

func (j *jsiiProxy_JdbcDataSource)SetEnableResourcePropertyConstraint(val *bool) {
	if err := j.validateSetEnableResourcePropertyConstraintParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"enableResourcePropertyConstraint",
		val,
	)
}

func (j *jsiiProxy_JdbcDataSource)SetId(val *string) {
	if err := j.validateSetIdParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"id",
		val,
	)
}

func (j *jsiiProxy_JdbcDataSource)SetResource(val alicloudroscdkcore.RosResource) {
	_jsii_.Set(
		j,
		"resource",
		val,
	)
}

func (j *jsiiProxy_JdbcDataSource)SetScope(val alicloudroscdkcore.Construct) {
	if err := j.validateSetScopeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"scope",
		val,
	)
}

// Return whether the given object is a Construct.
func JdbcDataSource_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateJdbcDataSource_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@alicloud/ros-cdk-gpdb.JdbcDataSource",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func (j *jsiiProxy_JdbcDataSource) AddCondition(condition alicloudroscdkcore.RosCondition) {
	if err := j.validateAddConditionParameters(condition); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		j,
		"addCondition",
		[]interface{}{condition},
	)
}

func (j *jsiiProxy_JdbcDataSource) AddCount(count interface{}) {
	if err := j.validateAddCountParameters(count); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		j,
		"addCount",
		[]interface{}{count},
	)
}

func (j *jsiiProxy_JdbcDataSource) AddDependency(resource alicloudroscdkcore.Resource) {
	if err := j.validateAddDependencyParameters(resource); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		j,
		"addDependency",
		[]interface{}{resource},
	)
}

func (j *jsiiProxy_JdbcDataSource) AddResourceDesc(desc *string) {
	if err := j.validateAddResourceDescParameters(desc); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		j,
		"addResourceDesc",
		[]interface{}{desc},
	)
}

func (j *jsiiProxy_JdbcDataSource) ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy) {
	if err := j.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		j,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (j *jsiiProxy_JdbcDataSource) FetchCondition() alicloudroscdkcore.RosCondition {
	var returns alicloudroscdkcore.RosCondition

	_jsii_.Invoke(
		j,
		"fetchCondition",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (j *jsiiProxy_JdbcDataSource) FetchDependency() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		j,
		"fetchDependency",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (j *jsiiProxy_JdbcDataSource) FetchResourceDesc() *string {
	var returns *string

	_jsii_.Invoke(
		j,
		"fetchResourceDesc",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (j *jsiiProxy_JdbcDataSource) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		j,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (j *jsiiProxy_JdbcDataSource) GetAtt(name *string) alicloudroscdkcore.IResolvable {
	if err := j.validateGetAttParameters(name); err != nil {
		panic(err)
	}
	var returns alicloudroscdkcore.IResolvable

	_jsii_.Invoke(
		j,
		"getAtt",
		[]interface{}{name},
		&returns,
	)

	return returns
}

func (j *jsiiProxy_JdbcDataSource) OnPrepare() {
	_jsii_.InvokeVoid(
		j,
		"onPrepare",
		nil, // no parameters
	)
}

func (j *jsiiProxy_JdbcDataSource) OnSynthesize(session constructs.ISynthesisSession) {
	if err := j.validateOnSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		j,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (j *jsiiProxy_JdbcDataSource) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		j,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (j *jsiiProxy_JdbcDataSource) Prepare() {
	_jsii_.InvokeVoid(
		j,
		"prepare",
		nil, // no parameters
	)
}

func (j *jsiiProxy_JdbcDataSource) SetMetadata(key *string, value interface{}) {
	if err := j.validateSetMetadataParameters(key, value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		j,
		"setMetadata",
		[]interface{}{key, value},
	)
}

func (j *jsiiProxy_JdbcDataSource) Synthesize(session alicloudroscdkcore.ISynthesisSession) {
	if err := j.validateSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		j,
		"synthesize",
		[]interface{}{session},
	)
}

func (j *jsiiProxy_JdbcDataSource) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		j,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (j *jsiiProxy_JdbcDataSource) Validate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		j,
		"validate",
		nil, // no parameters
		&returns,
	)

	return returns
}

