package alicloudroscdkvpc

import (
	_init_ "github.com/alibabacloud-go/ros-cdk/alicloudroscdkvpc/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkcore"
	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkvpc/internal"
	"github.com/aws/constructs-go/constructs/v3"
)

// This class encapsulates and extends the ROS resource type `ALIYUN::VPC::TrafficQosRule`.
type TrafficQosRule interface {
	alicloudroscdkcore.Resource
	ITrafficQosRule
	// Attribute DstCidr: The destination IPv4 CIDR block that matches the QoS rule traffic.
	AttrDstCidr() interface{}
	// Attribute DstIpv6Cidr: The QoS rule traffic matches the Destination IPv6 network segment.
	AttrDstIpv6Cidr() interface{}
	// Attribute DstPortRange: QoS rule traffic matches the destination port number range.
	//
	// Value range: **0** to **65535**. If not, the value is -1. Currently, only a single port number is supported, and the start and end of the port number must be the same. The corresponding destination port number range is fixed for different protocol types.
	AttrDstPortRange() interface{}
	// Attribute MatchDscp: The DSCP value of the traffic matched by the QoS rule.
	//
	// Value range: **0** to **63**. If not, the value is -1.
	AttrMatchDscp() interface{}
	// Attribute Priority: QoS rule priority.
	//
	// Value range: **1** to **9000**. The larger the number, the higher the priority. The priority of a QoS rule cannot be repeated in the same QoS policy.
	AttrPriority() interface{}
	// Attribute Protocol: QoS rule protocol type.
	AttrProtocol() interface{}
	// Attribute QosId: The QoS policy ID.
	AttrQosId() interface{}
	// Attribute QueueId: The QoS queue ID.
	AttrQueueId() interface{}
	// Attribute RemarkingDscp: Modify The DSCP value in the flow.
	//
	// Value range: **0** to **63**. If the value is not modified, the value is -1.
	AttrRemarkingDscp() interface{}
	// Attribute RuleDescription: The description of the QoS rule.
	AttrRuleDescription() interface{}
	// Attribute RuleId: The ID of the QoS rule.
	AttrRuleId() interface{}
	// Attribute RuleName: The name of the QoS rule.
	AttrRuleName() interface{}
	// Attribute SrcCidr: The source IPv4 CIDR block that matches the QoS rule traffic.
	AttrSrcCidr() interface{}
	// Attribute SrcIpv6Cidr: The QoS rule traffic matches the source IPv6 network segment.
	AttrSrcIpv6Cidr() interface{}
	// Attribute SrcPortRange: The source port number of the QoS rule traffic matching.
	//
	// The value range is **0** to **65535**. If the traffic does not match, the value is -1. Currently, only a single port number is supported, and the start and end of the port number must be the same.
	AttrSrcPortRange() interface{}
	EnableResourcePropertyConstraint() *bool
	SetEnableResourcePropertyConstraint(val *bool)
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() alicloudroscdkcore.IResourceEnvironment
	Id() *string
	SetId(val *string)
	// The construct tree node associated with this construct.
	Node() alicloudroscdkcore.ConstructNode
	// Returns a string-encoded token that resolves to the physical name that should be passed to the ROS resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by ROS
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	Props() *TrafficQosRuleProps
	Ref() *string
	Resource() alicloudroscdkcore.RosResource
	SetResource(val alicloudroscdkcore.RosResource)
	Scope() alicloudroscdkcore.Construct
	SetScope(val alicloudroscdkcore.Construct)
	// The stack in which this resource is defined.
	Stack() alicloudroscdkcore.Stack
	AddCondition(condition alicloudroscdkcore.RosCondition)
	AddCount(count interface{})
	AddDependency(resource alicloudroscdkcore.Resource)
	AddResourceDesc(desc *string)
	ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy)
	FetchCondition() alicloudroscdkcore.RosCondition
	FetchDependency() *[]*string
	FetchResourceDesc() *string
	GeneratePhysicalName() *string
	GetAtt(name *string) alicloudroscdkcore.IResolvable
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	OnValidate() *[]*string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	Prepare()
	SetMetadata(key *string, value interface{})
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	Synthesize(session alicloudroscdkcore.ISynthesisSession)
	// Returns a string representation of this construct.
	ToString() *string
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	Validate() *[]*string
}

// The jsii proxy struct for TrafficQosRule
type jsiiProxy_TrafficQosRule struct {
	internal.Type__alicloudroscdkcoreResource
	jsiiProxy_ITrafficQosRule
}

func (j *jsiiProxy_TrafficQosRule) AttrDstCidr() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrDstCidr",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrDstIpv6Cidr() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrDstIpv6Cidr",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrDstPortRange() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrDstPortRange",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrMatchDscp() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrMatchDscp",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrPriority() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrPriority",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrProtocol() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrProtocol",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrQosId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrQosId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrQueueId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrQueueId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrRemarkingDscp() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrRemarkingDscp",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrRuleDescription() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrRuleDescription",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrRuleId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrRuleId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrRuleName() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrRuleName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrSrcCidr() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrSrcCidr",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrSrcIpv6Cidr() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrSrcIpv6Cidr",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) AttrSrcPortRange() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrSrcPortRange",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) EnableResourcePropertyConstraint() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"enableResourcePropertyConstraint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) Env() alicloudroscdkcore.IResourceEnvironment {
	var returns alicloudroscdkcore.IResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) Id() *string {
	var returns *string
	_jsii_.Get(
		j,
		"id",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) Node() alicloudroscdkcore.ConstructNode {
	var returns alicloudroscdkcore.ConstructNode
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) Props() *TrafficQosRuleProps {
	var returns *TrafficQosRuleProps
	_jsii_.Get(
		j,
		"props",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) Ref() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ref",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) Resource() alicloudroscdkcore.RosResource {
	var returns alicloudroscdkcore.RosResource
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) Scope() alicloudroscdkcore.Construct {
	var returns alicloudroscdkcore.Construct
	_jsii_.Get(
		j,
		"scope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_TrafficQosRule) Stack() alicloudroscdkcore.Stack {
	var returns alicloudroscdkcore.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewTrafficQosRule(scope alicloudroscdkcore.Construct, id *string, props *TrafficQosRuleProps, enableResourcePropertyConstraint *bool) TrafficQosRule {
	_init_.Initialize()

	if err := validateNewTrafficQosRuleParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_TrafficQosRule{}

	_jsii_.Create(
		"@alicloud/ros-cdk-vpc.TrafficQosRule",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		&j,
	)

	return &j
}

// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewTrafficQosRule_Override(t TrafficQosRule, scope alicloudroscdkcore.Construct, id *string, props *TrafficQosRuleProps, enableResourcePropertyConstraint *bool) {
	_init_.Initialize()

	_jsii_.Create(
		"@alicloud/ros-cdk-vpc.TrafficQosRule",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		t,
	)
}

func (j *jsiiProxy_TrafficQosRule)SetEnableResourcePropertyConstraint(val *bool) {
	if err := j.validateSetEnableResourcePropertyConstraintParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"enableResourcePropertyConstraint",
		val,
	)
}

func (j *jsiiProxy_TrafficQosRule)SetId(val *string) {
	if err := j.validateSetIdParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"id",
		val,
	)
}

func (j *jsiiProxy_TrafficQosRule)SetResource(val alicloudroscdkcore.RosResource) {
	_jsii_.Set(
		j,
		"resource",
		val,
	)
}

func (j *jsiiProxy_TrafficQosRule)SetScope(val alicloudroscdkcore.Construct) {
	if err := j.validateSetScopeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"scope",
		val,
	)
}

// Return whether the given object is a Construct.
func TrafficQosRule_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateTrafficQosRule_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@alicloud/ros-cdk-vpc.TrafficQosRule",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func (t *jsiiProxy_TrafficQosRule) AddCondition(condition alicloudroscdkcore.RosCondition) {
	if err := t.validateAddConditionParameters(condition); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		t,
		"addCondition",
		[]interface{}{condition},
	)
}

func (t *jsiiProxy_TrafficQosRule) AddCount(count interface{}) {
	if err := t.validateAddCountParameters(count); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		t,
		"addCount",
		[]interface{}{count},
	)
}

func (t *jsiiProxy_TrafficQosRule) AddDependency(resource alicloudroscdkcore.Resource) {
	if err := t.validateAddDependencyParameters(resource); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		t,
		"addDependency",
		[]interface{}{resource},
	)
}

func (t *jsiiProxy_TrafficQosRule) AddResourceDesc(desc *string) {
	if err := t.validateAddResourceDescParameters(desc); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		t,
		"addResourceDesc",
		[]interface{}{desc},
	)
}

func (t *jsiiProxy_TrafficQosRule) ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy) {
	if err := t.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		t,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (t *jsiiProxy_TrafficQosRule) FetchCondition() alicloudroscdkcore.RosCondition {
	var returns alicloudroscdkcore.RosCondition

	_jsii_.Invoke(
		t,
		"fetchCondition",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (t *jsiiProxy_TrafficQosRule) FetchDependency() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		t,
		"fetchDependency",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (t *jsiiProxy_TrafficQosRule) FetchResourceDesc() *string {
	var returns *string

	_jsii_.Invoke(
		t,
		"fetchResourceDesc",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (t *jsiiProxy_TrafficQosRule) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		t,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (t *jsiiProxy_TrafficQosRule) GetAtt(name *string) alicloudroscdkcore.IResolvable {
	if err := t.validateGetAttParameters(name); err != nil {
		panic(err)
	}
	var returns alicloudroscdkcore.IResolvable

	_jsii_.Invoke(
		t,
		"getAtt",
		[]interface{}{name},
		&returns,
	)

	return returns
}

func (t *jsiiProxy_TrafficQosRule) OnPrepare() {
	_jsii_.InvokeVoid(
		t,
		"onPrepare",
		nil, // no parameters
	)
}

func (t *jsiiProxy_TrafficQosRule) OnSynthesize(session constructs.ISynthesisSession) {
	if err := t.validateOnSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		t,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (t *jsiiProxy_TrafficQosRule) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		t,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (t *jsiiProxy_TrafficQosRule) Prepare() {
	_jsii_.InvokeVoid(
		t,
		"prepare",
		nil, // no parameters
	)
}

func (t *jsiiProxy_TrafficQosRule) SetMetadata(key *string, value interface{}) {
	if err := t.validateSetMetadataParameters(key, value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		t,
		"setMetadata",
		[]interface{}{key, value},
	)
}

func (t *jsiiProxy_TrafficQosRule) Synthesize(session alicloudroscdkcore.ISynthesisSession) {
	if err := t.validateSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		t,
		"synthesize",
		[]interface{}{session},
	)
}

func (t *jsiiProxy_TrafficQosRule) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		t,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (t *jsiiProxy_TrafficQosRule) Validate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		t,
		"validate",
		nil, // no parameters
		&returns,
	)

	return returns
}

