package datasource

import (
	_init_ "github.com/alibabacloud-go/ros-cdk/alicloudroscdkarms/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkarms/datasource/internal"
	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkcore"
	"github.com/aws/constructs-go/constructs/v3"
)

// This class encapsulates and extends the ROS resource type `DATASOURCE::ARMS::XTraceApps`, which is used to query all the application monitoring tasks in a region.
type XTraceApps interface {
	alicloudroscdkcore.Resource
	IXTraceApps
	// Attribute Pids: The list of Pids.
	AttrPids() interface{}
	// Attribute XTraceApps: The list of Application Monitoring tasks.
	AttrXTraceApps() interface{}
	EnableResourcePropertyConstraint() *bool
	SetEnableResourcePropertyConstraint(val *bool)
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() alicloudroscdkcore.IResourceEnvironment
	Id() *string
	SetId(val *string)
	// The construct tree node associated with this construct.
	Node() alicloudroscdkcore.ConstructNode
	// Returns a string-encoded token that resolves to the physical name that should be passed to the ROS resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by ROS
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	Props() *XTraceAppsProps
	Ref() *string
	Resource() alicloudroscdkcore.RosResource
	SetResource(val alicloudroscdkcore.RosResource)
	Scope() alicloudroscdkcore.Construct
	SetScope(val alicloudroscdkcore.Construct)
	// The stack in which this resource is defined.
	Stack() alicloudroscdkcore.Stack
	AddCondition(condition alicloudroscdkcore.RosCondition)
	AddCount(count interface{})
	AddDependency(resource alicloudroscdkcore.Resource)
	AddResourceDesc(desc *string)
	ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy)
	FetchCondition() alicloudroscdkcore.RosCondition
	FetchDependency() *[]*string
	FetchResourceDesc() *string
	GeneratePhysicalName() *string
	GetAtt(name *string) alicloudroscdkcore.IResolvable
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	OnValidate() *[]*string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	Prepare()
	SetMetadata(key *string, value interface{})
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	Synthesize(session alicloudroscdkcore.ISynthesisSession)
	// Returns a string representation of this construct.
	ToString() *string
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	Validate() *[]*string
}

// The jsii proxy struct for XTraceApps
type jsiiProxy_XTraceApps struct {
	internal.Type__alicloudroscdkcoreResource
	jsiiProxy_IXTraceApps
}

func (j *jsiiProxy_XTraceApps) AttrPids() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrPids",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_XTraceApps) AttrXTraceApps() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrXTraceApps",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_XTraceApps) EnableResourcePropertyConstraint() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"enableResourcePropertyConstraint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_XTraceApps) Env() alicloudroscdkcore.IResourceEnvironment {
	var returns alicloudroscdkcore.IResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_XTraceApps) Id() *string {
	var returns *string
	_jsii_.Get(
		j,
		"id",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_XTraceApps) Node() alicloudroscdkcore.ConstructNode {
	var returns alicloudroscdkcore.ConstructNode
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_XTraceApps) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_XTraceApps) Props() *XTraceAppsProps {
	var returns *XTraceAppsProps
	_jsii_.Get(
		j,
		"props",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_XTraceApps) Ref() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ref",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_XTraceApps) Resource() alicloudroscdkcore.RosResource {
	var returns alicloudroscdkcore.RosResource
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_XTraceApps) Scope() alicloudroscdkcore.Construct {
	var returns alicloudroscdkcore.Construct
	_jsii_.Get(
		j,
		"scope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_XTraceApps) Stack() alicloudroscdkcore.Stack {
	var returns alicloudroscdkcore.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewXTraceApps(scope alicloudroscdkcore.Construct, id *string, props *XTraceAppsProps, enableResourcePropertyConstraint *bool) XTraceApps {
	_init_.Initialize()

	if err := validateNewXTraceAppsParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_XTraceApps{}

	_jsii_.Create(
		"@alicloud/ros-cdk-arms.datasource.XTraceApps",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		&j,
	)

	return &j
}

// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewXTraceApps_Override(x XTraceApps, scope alicloudroscdkcore.Construct, id *string, props *XTraceAppsProps, enableResourcePropertyConstraint *bool) {
	_init_.Initialize()

	_jsii_.Create(
		"@alicloud/ros-cdk-arms.datasource.XTraceApps",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		x,
	)
}

func (j *jsiiProxy_XTraceApps)SetEnableResourcePropertyConstraint(val *bool) {
	if err := j.validateSetEnableResourcePropertyConstraintParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"enableResourcePropertyConstraint",
		val,
	)
}

func (j *jsiiProxy_XTraceApps)SetId(val *string) {
	if err := j.validateSetIdParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"id",
		val,
	)
}

func (j *jsiiProxy_XTraceApps)SetResource(val alicloudroscdkcore.RosResource) {
	_jsii_.Set(
		j,
		"resource",
		val,
	)
}

func (j *jsiiProxy_XTraceApps)SetScope(val alicloudroscdkcore.Construct) {
	if err := j.validateSetScopeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"scope",
		val,
	)
}

// Return whether the given object is a Construct.
func XTraceApps_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateXTraceApps_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@alicloud/ros-cdk-arms.datasource.XTraceApps",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func (x *jsiiProxy_XTraceApps) AddCondition(condition alicloudroscdkcore.RosCondition) {
	if err := x.validateAddConditionParameters(condition); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		x,
		"addCondition",
		[]interface{}{condition},
	)
}

func (x *jsiiProxy_XTraceApps) AddCount(count interface{}) {
	if err := x.validateAddCountParameters(count); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		x,
		"addCount",
		[]interface{}{count},
	)
}

func (x *jsiiProxy_XTraceApps) AddDependency(resource alicloudroscdkcore.Resource) {
	if err := x.validateAddDependencyParameters(resource); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		x,
		"addDependency",
		[]interface{}{resource},
	)
}

func (x *jsiiProxy_XTraceApps) AddResourceDesc(desc *string) {
	if err := x.validateAddResourceDescParameters(desc); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		x,
		"addResourceDesc",
		[]interface{}{desc},
	)
}

func (x *jsiiProxy_XTraceApps) ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy) {
	if err := x.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		x,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (x *jsiiProxy_XTraceApps) FetchCondition() alicloudroscdkcore.RosCondition {
	var returns alicloudroscdkcore.RosCondition

	_jsii_.Invoke(
		x,
		"fetchCondition",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (x *jsiiProxy_XTraceApps) FetchDependency() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		x,
		"fetchDependency",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (x *jsiiProxy_XTraceApps) FetchResourceDesc() *string {
	var returns *string

	_jsii_.Invoke(
		x,
		"fetchResourceDesc",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (x *jsiiProxy_XTraceApps) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		x,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (x *jsiiProxy_XTraceApps) GetAtt(name *string) alicloudroscdkcore.IResolvable {
	if err := x.validateGetAttParameters(name); err != nil {
		panic(err)
	}
	var returns alicloudroscdkcore.IResolvable

	_jsii_.Invoke(
		x,
		"getAtt",
		[]interface{}{name},
		&returns,
	)

	return returns
}

func (x *jsiiProxy_XTraceApps) OnPrepare() {
	_jsii_.InvokeVoid(
		x,
		"onPrepare",
		nil, // no parameters
	)
}

func (x *jsiiProxy_XTraceApps) OnSynthesize(session constructs.ISynthesisSession) {
	if err := x.validateOnSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		x,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (x *jsiiProxy_XTraceApps) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		x,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (x *jsiiProxy_XTraceApps) Prepare() {
	_jsii_.InvokeVoid(
		x,
		"prepare",
		nil, // no parameters
	)
}

func (x *jsiiProxy_XTraceApps) SetMetadata(key *string, value interface{}) {
	if err := x.validateSetMetadataParameters(key, value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		x,
		"setMetadata",
		[]interface{}{key, value},
	)
}

func (x *jsiiProxy_XTraceApps) Synthesize(session alicloudroscdkcore.ISynthesisSession) {
	if err := x.validateSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		x,
		"synthesize",
		[]interface{}{session},
	)
}

func (x *jsiiProxy_XTraceApps) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		x,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (x *jsiiProxy_XTraceApps) Validate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		x,
		"validate",
		nil, // no parameters
		&returns,
	)

	return returns
}

