package alicloudroscdkpai


// Properties for defining a `Dataset`.
//
// See https://www.alibabacloud.com/help/ros/developer-reference/aliyun-pai-dataset
type DatasetProps struct {
	// Property datasetName: The name of the dataset.
	//
	// The naming rules are as follows:
	// - Start with a lowercase letter, uppercase letter, number, or Chinese.
	// - Can contain an underscore (_) or a dash (-).
	// - 1~127 characters in length.
	DatasetName interface{} `field:"required" json:"datasetName" yaml:"datasetName"`
	// Property dataSourceType: The data source type.
	//
	// The following values are supported:
	// - OSS: Alibaba Cloud Object Storage (OSS).
	// - NAS: Alibaba cloud file storage (NAS).
	DataSourceType interface{} `field:"required" json:"dataSourceType" yaml:"dataSourceType"`
	// Property property: The properties of the dataset.
	//
	// The following values are supported:
	// - FILE: FILE.
	// - DIRECTORY: folder.
	Property interface{} `field:"required" json:"property" yaml:"property"`
	// Property uri: The Uri configuration sample is as follows: - The data source type is OSS:'oss:\/\/ bucket.endpoint\/object' - The data source type is NAS: The general NAS format is: 'nas:\/\/<nasfisid>.region\/subpath\/to\/dir\/'; CPFS1.0:'nas:\/\/<cpfs-fsid>.region\/subpath\/to\/dir \/'; CPFS2.0:'nas:\/\/<cpfs-fsid>.region\/<protocolserviceid>\/'. CPFS1.0 and CPFS2.0 are distinguished by the format of fsid: CPFS1.0 is cpfs-<8-bit ascii characters>;CPFS2.0 is cpfs-<16 ascii characters>.
	Uri interface{} `field:"required" json:"uri" yaml:"uri"`
	// Property workspaceId: The ID of the workspace where the dataset is located.
	//
	// For details about how to obtain the workspace ID, see [ListWorkspaces](~~ 449124 ~~).
	// If this parameter is not configured, the default workspace is used. If the default workspace does not exist, an error is reported.
	WorkspaceId interface{} `field:"required" json:"workspaceId" yaml:"workspaceId"`
	// Property accessibility: Workspace visibility.
	//
	// The following values are supported:
	// - PRIVATE (default): indicates that the workspace is visible to itself and the administrator.
	// - PUBLIC: The workspace is visible to all users.
	Accessibility interface{} `field:"optional" json:"accessibility" yaml:"accessibility"`
	// Property dataType: The dataset type.
	//
	// The default value is COMMON. The following values are supported:
	// - COMMON: COMMON.
	// - PIC: picture.
	// - TEXT: TEXT.
	// - VIDEO: VIDEO.
	// - AUDIO: AUDIO.
	DataType interface{} `field:"optional" json:"dataType" yaml:"dataType"`
	// Property description: Custom descriptions of datasets to distinguish between different datasets.
	Description interface{} `field:"optional" json:"description" yaml:"description"`
	// Property options: The extended field, which is of the JsonString type.
	//
	// When DLC uses a dataset, you can specify the default Mount path for the dataset by configuring the mountPath field.
	Options interface{} `field:"optional" json:"options" yaml:"options"`
	// Property sourceId: The data source ID.
	//
	// - When the SourceType is USER, SourceId can be customized.
	// - When SourceType is ITAG, that is, when the iTAG module labels the data set generated by the result, SourceId is the task ID of ITAG.
	// - When SourceType is PAI_PUBLIC_DATASET, that is, a dataset created using PAI public datasets, SourceId is empty by default.
	SourceId interface{} `field:"optional" json:"sourceId" yaml:"sourceId"`
	// Property sourceType: The data source type.
	//
	// The default value is USER. The following values are supported:
	// - PAI-PUBLIC-DATASET:PAI public dataset.
	// - ITAG: The dataset generated by the iTAG module annotation result.
	// - USER: The data set registered by the USER.
	SourceType interface{} `field:"optional" json:"sourceType" yaml:"sourceType"`
}

