package alicloudroscdkpai


// Properties for defining a `DatasetVersion`.
//
// See https://www.alibabacloud.com/help/ros/developer-reference/aliyun-pai-datasetversion
type DatasetVersionProps struct {
	// Property datasetId: The ID of the dataset.
	DatasetId interface{} `field:"required" json:"datasetId" yaml:"datasetId"`
	// Property dataSourceType: The data source type.
	//
	// The following values are supported:
	// - OSS: Alibaba Cloud Object Storage (OSS).
	// - NAS: Alibaba cloud file storage (NAS).
	// - CPFS.
	DataSourceType interface{} `field:"required" json:"dataSourceType" yaml:"dataSourceType"`
	// Property property: The properties of the dataset.
	//
	// The following values are supported:
	// - FILE: FILE.
	// - DIRECTORY: folder.
	Property interface{} `field:"required" json:"property" yaml:"property"`
	// Property uri: The Uri configuration sample is as follows: - The data source type is OSS:'oss:\/\/bucket.endpoint\/object' - The data source type is NAS: The general NAS format is: 'nas:\/\/<nasfisid>.region\/subpath\/to\/dir\/'; CPFS1.0:'nas:\/\/<cpfs-fsid>.region\/subpath\/to\/dir \/'; CPFS2.0:'nas:\/\/<cpfs-fsid>.region\/<protocolserviceid>\/'. CPFS1.0 and CPFS2.0 are distinguished by the format of fsid: CPFS1.0 is cpfs-<8-bit ascii characters>;CPFS2.0 is cpfs-<16 ascii characters>.
	Uri interface{} `field:"required" json:"uri" yaml:"uri"`
	// Property dataCount: The number of dataset files, in units of pieces.
	DataCount interface{} `field:"optional" json:"dataCount" yaml:"dataCount"`
	// Property dataSize: The size of the dataset file in bytes.
	DataSize interface{} `field:"optional" json:"dataSize" yaml:"dataSize"`
	// Property description: To create a custom description for dataset versions in order to distinguish between different versions of the dataset.
	Description interface{} `field:"optional" json:"description" yaml:"description"`
	// Property labels: Dataset version tag list.
	Labels interface{} `field:"optional" json:"labels" yaml:"labels"`
	// Property options: The extended field, which is of the JsonString type.
	//
	// When DLC uses a dataset, you can specify the default Mount path for the dataset by configuring the mountPath field.
	Options interface{} `field:"optional" json:"options" yaml:"options"`
	// Property sourceId: The data source ID.
	//
	// - When the SourceType is USER, SourceId can be customized.
	// - When SourceType is ITAG, that is, when the iTAG module labels the data set generated by the result, SourceId is the task ID of ITAG.
	// - When SourceType is PAI_PUBLIC_DATASET, that is, a dataset created using PAI public datasets, SourceId is empty by default.
	SourceId interface{} `field:"optional" json:"sourceId" yaml:"sourceId"`
	// Property sourceType: The data source type.
	//
	// The default value is USER. The following values are supported:
	// - PAI-PUBLIC-DATASET:PAI public dataset.
	// - ITAG: The dataset generated by the iTAG module annotation result.
	// - USER: The data set registered by the USER.
	SourceType interface{} `field:"optional" json:"sourceType" yaml:"sourceType"`
}

