package alicloudroscdkpai

import (
	_init_ "github.com/alibabacloud-go/ros-cdk/alicloudroscdkpai/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkcore"
	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkpai/internal"
	"github.com/aws/constructs-go/constructs/v3"
)

// This class encapsulates and extends the ROS resource type `ALIYUN::PAI::ModelVersion`.
type ModelVersion interface {
	alicloudroscdkcore.Resource
	IModelVersion
	// Attribute ApprovalStatus: Admission status, with values as follows:.
	AttrApprovalStatus() interface{}
	// Attribute ExtraInfo: Other information.
	AttrExtraInfo() interface{}
	// Attribute FormatType: Model format, possible values:.
	AttrFormatType() interface{}
	// Attribute FrameworkType: Model framework, possible values:.
	AttrFrameworkType() interface{}
	// Attribute GmtCreateTime: Create a model UTC time in the format ISO8601.
	AttrGmtCreateTime() interface{}
	// Attribute GmtModifiedTime: Finally, update the model UTC time in the format iso8601.
	AttrGmtModifiedTime() interface{}
	// Attribute InferenceSpec: Describes how to apply to downstream inference services, such as processors and containers of EAS.
	AttrInferenceSpec() interface{}
	// Attribute Labels: List of model version labels.
	AttrLabels() interface{}
	// Attribute Metrics: Model indicators.
	AttrMetrics() interface{}
	// Attribute Options: Extension field.
	//
	// The JsonString type.
	AttrOptions() interface{}
	// Attribute OwnerId: The Alibaba Cloud account ID.
	AttrOwnerId() interface{}
	// Attribute SourceId: Source ID.
	AttrSourceId() interface{}
	// Attribute SourceType: Model source type, possible values:.
	AttrSourceType() interface{}
	// Attribute TrainingSpec: Training configuration.
	//
	// Configuration for fine-tuning, incremental training.
	AttrTrainingSpec() interface{}
	// Attribute Uri: Model version URI, that is, the location where the model is stored.
	AttrUri() interface{}
	// Attribute UserId: The user ID.
	AttrUserId() interface{}
	// Attribute VersionDescription: Model version description.
	AttrVersionDescription() interface{}
	// Attribute VersionName: Model version.
	AttrVersionName() interface{}
	EnableResourcePropertyConstraint() *bool
	SetEnableResourcePropertyConstraint(val *bool)
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() alicloudroscdkcore.IResourceEnvironment
	Id() *string
	SetId(val *string)
	// The construct tree node associated with this construct.
	Node() alicloudroscdkcore.ConstructNode
	// Returns a string-encoded token that resolves to the physical name that should be passed to the ROS resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by ROS
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	Props() *ModelVersionProps
	Ref() *string
	Resource() alicloudroscdkcore.RosResource
	SetResource(val alicloudroscdkcore.RosResource)
	Scope() alicloudroscdkcore.Construct
	SetScope(val alicloudroscdkcore.Construct)
	// The stack in which this resource is defined.
	Stack() alicloudroscdkcore.Stack
	AddCondition(condition alicloudroscdkcore.RosCondition)
	AddCount(count interface{})
	AddDependency(resource alicloudroscdkcore.Resource)
	AddResourceDesc(desc *string)
	ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy)
	FetchCondition() alicloudroscdkcore.RosCondition
	FetchDependency() *[]*string
	FetchResourceDesc() *string
	GeneratePhysicalName() *string
	GetAtt(name *string) alicloudroscdkcore.IResolvable
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	OnValidate() *[]*string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	Prepare()
	SetMetadata(key *string, value interface{})
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	Synthesize(session alicloudroscdkcore.ISynthesisSession)
	// Returns a string representation of this construct.
	ToString() *string
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	Validate() *[]*string
}

// The jsii proxy struct for ModelVersion
type jsiiProxy_ModelVersion struct {
	internal.Type__alicloudroscdkcoreResource
	jsiiProxy_IModelVersion
}

func (j *jsiiProxy_ModelVersion) AttrApprovalStatus() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrApprovalStatus",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrExtraInfo() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrExtraInfo",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrFormatType() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrFormatType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrFrameworkType() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrFrameworkType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrGmtCreateTime() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrGmtCreateTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrGmtModifiedTime() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrGmtModifiedTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrInferenceSpec() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrInferenceSpec",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrLabels() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrLabels",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrMetrics() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrMetrics",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrOptions() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrOptions",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrOwnerId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrOwnerId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrSourceId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrSourceId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrSourceType() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrSourceType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrTrainingSpec() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrTrainingSpec",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrUri() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrUri",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrUserId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrUserId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrVersionDescription() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrVersionDescription",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) AttrVersionName() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrVersionName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) EnableResourcePropertyConstraint() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"enableResourcePropertyConstraint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) Env() alicloudroscdkcore.IResourceEnvironment {
	var returns alicloudroscdkcore.IResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) Id() *string {
	var returns *string
	_jsii_.Get(
		j,
		"id",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) Node() alicloudroscdkcore.ConstructNode {
	var returns alicloudroscdkcore.ConstructNode
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) Props() *ModelVersionProps {
	var returns *ModelVersionProps
	_jsii_.Get(
		j,
		"props",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) Ref() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ref",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) Resource() alicloudroscdkcore.RosResource {
	var returns alicloudroscdkcore.RosResource
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) Scope() alicloudroscdkcore.Construct {
	var returns alicloudroscdkcore.Construct
	_jsii_.Get(
		j,
		"scope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ModelVersion) Stack() alicloudroscdkcore.Stack {
	var returns alicloudroscdkcore.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewModelVersion(scope alicloudroscdkcore.Construct, id *string, props *ModelVersionProps, enableResourcePropertyConstraint *bool) ModelVersion {
	_init_.Initialize()

	if err := validateNewModelVersionParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_ModelVersion{}

	_jsii_.Create(
		"@alicloud/ros-cdk-pai.ModelVersion",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		&j,
	)

	return &j
}

// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewModelVersion_Override(m ModelVersion, scope alicloudroscdkcore.Construct, id *string, props *ModelVersionProps, enableResourcePropertyConstraint *bool) {
	_init_.Initialize()

	_jsii_.Create(
		"@alicloud/ros-cdk-pai.ModelVersion",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		m,
	)
}

func (j *jsiiProxy_ModelVersion)SetEnableResourcePropertyConstraint(val *bool) {
	if err := j.validateSetEnableResourcePropertyConstraintParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"enableResourcePropertyConstraint",
		val,
	)
}

func (j *jsiiProxy_ModelVersion)SetId(val *string) {
	if err := j.validateSetIdParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"id",
		val,
	)
}

func (j *jsiiProxy_ModelVersion)SetResource(val alicloudroscdkcore.RosResource) {
	_jsii_.Set(
		j,
		"resource",
		val,
	)
}

func (j *jsiiProxy_ModelVersion)SetScope(val alicloudroscdkcore.Construct) {
	if err := j.validateSetScopeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"scope",
		val,
	)
}

// Return whether the given object is a Construct.
func ModelVersion_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateModelVersion_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@alicloud/ros-cdk-pai.ModelVersion",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func (m *jsiiProxy_ModelVersion) AddCondition(condition alicloudroscdkcore.RosCondition) {
	if err := m.validateAddConditionParameters(condition); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		m,
		"addCondition",
		[]interface{}{condition},
	)
}

func (m *jsiiProxy_ModelVersion) AddCount(count interface{}) {
	if err := m.validateAddCountParameters(count); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		m,
		"addCount",
		[]interface{}{count},
	)
}

func (m *jsiiProxy_ModelVersion) AddDependency(resource alicloudroscdkcore.Resource) {
	if err := m.validateAddDependencyParameters(resource); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		m,
		"addDependency",
		[]interface{}{resource},
	)
}

func (m *jsiiProxy_ModelVersion) AddResourceDesc(desc *string) {
	if err := m.validateAddResourceDescParameters(desc); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		m,
		"addResourceDesc",
		[]interface{}{desc},
	)
}

func (m *jsiiProxy_ModelVersion) ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy) {
	if err := m.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		m,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (m *jsiiProxy_ModelVersion) FetchCondition() alicloudroscdkcore.RosCondition {
	var returns alicloudroscdkcore.RosCondition

	_jsii_.Invoke(
		m,
		"fetchCondition",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (m *jsiiProxy_ModelVersion) FetchDependency() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		m,
		"fetchDependency",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (m *jsiiProxy_ModelVersion) FetchResourceDesc() *string {
	var returns *string

	_jsii_.Invoke(
		m,
		"fetchResourceDesc",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (m *jsiiProxy_ModelVersion) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		m,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (m *jsiiProxy_ModelVersion) GetAtt(name *string) alicloudroscdkcore.IResolvable {
	if err := m.validateGetAttParameters(name); err != nil {
		panic(err)
	}
	var returns alicloudroscdkcore.IResolvable

	_jsii_.Invoke(
		m,
		"getAtt",
		[]interface{}{name},
		&returns,
	)

	return returns
}

func (m *jsiiProxy_ModelVersion) OnPrepare() {
	_jsii_.InvokeVoid(
		m,
		"onPrepare",
		nil, // no parameters
	)
}

func (m *jsiiProxy_ModelVersion) OnSynthesize(session constructs.ISynthesisSession) {
	if err := m.validateOnSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		m,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (m *jsiiProxy_ModelVersion) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		m,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (m *jsiiProxy_ModelVersion) Prepare() {
	_jsii_.InvokeVoid(
		m,
		"prepare",
		nil, // no parameters
	)
}

func (m *jsiiProxy_ModelVersion) SetMetadata(key *string, value interface{}) {
	if err := m.validateSetMetadataParameters(key, value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		m,
		"setMetadata",
		[]interface{}{key, value},
	)
}

func (m *jsiiProxy_ModelVersion) Synthesize(session alicloudroscdkcore.ISynthesisSession) {
	if err := m.validateSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		m,
		"synthesize",
		[]interface{}{session},
	)
}

func (m *jsiiProxy_ModelVersion) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		m,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (m *jsiiProxy_ModelVersion) Validate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		m,
		"validate",
		nil, // no parameters
		&returns,
	)

	return returns
}

