[build-system]
requires = ["setuptools~=67.3.2", "wheel~=0.41"]
build-backend = "setuptools.build_meta"

[tool.pyright]
defineConstant = { DEBUG = true }
pythonVersion = "3.7"
pythonPlatform = "All"
reportSelfClsParameterName = false
