using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace AlibabaCloud.SDK.ROS.CDK.Cms
{
    #pragma warning disable CS8618

    /// <summary>Properties for defining a `ALIYUN::CMS::GroupMetricRule`.</summary>
    [JsiiByValue(fqn: "@alicloud/ros-cdk-cms.RosGroupMetricRuleProps")]
    public class RosGroupMetricRuleProps : AlibabaCloud.SDK.ROS.CDK.Cms.IRosGroupMetricRuleProps
    {
        /// <remarks>
        /// <strong>Property</strong>: category: The abbreviation of the service name. Valid values:
        /// ECS (including Alibaba Cloud and non-Alibaba Cloud hosts)
        /// RDS (ApsaraDB for RDS)
        /// ADS (AnalyticDB)
        /// SLB (Server Load Balancer)
        /// VPC (Virtual Private Cloud)
        /// APIGATEWAY (API Gateway)
        /// CDN
        /// CS (Container Service for Swarm)
        /// DCDN (Dynamic Route for CDN)
        /// DDoS (distributed denial of service)
        /// EIP (Elastic IP)
        /// ELASTICSEARCH (Elasticsearch)
        /// EMR (E-MapReduce)
        /// ESS (Auto Scaling)
        /// HBASE (ApsaraDB for HBase)
        /// IOT_EDGE (IoT Edge)
        /// K8S_POD (k8s pod)
        /// KVSTORE_SHARDING (ApsaraDB for Redis cluster version)
        /// KVSTORE_SPLITRW (ApsaraDB for Redis read/write splitting version)
        /// KVSTORE_STANDARD (ApsaraDB for Redis standard version)
        /// MEMCACHE (ApsaraDB for Memcache)
        /// MNS (Message Service)
        /// MONGODB (ApsaraDB for MongoDB replica set instances)
        /// MONGODB_CLUSTER (ApsaraDB for MongoDB cluster version)
        /// MONGODB_SHARDING (ApsaraDB for MongoDB sharded clusters)
        /// MQ_TOPIC (Message Service topic)
        /// OCS (original version of ApsaraDB for Memcache)
        /// OPENSEARCH (Open Search)
        /// OSS (Object Storage Service)
        /// POLARDB (ApsaraDB for POLARDB)
        /// PETADATA (HybridDB for MySQL)
        /// SCDN (Secure Content Delivery Network)
        /// SHAREBANDWIDTHPACKAGES (shared bandwidth package)
        /// SLS (Log Service)
        /// VPN (VPN Gateway)
        /// </remarks>
        [JsiiProperty(name: "category", typeJson: "{\"primitive\":\"string\"}", isOverride: true)]
        public string Category
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: escalations: undefined
        /// </remarks>
        [JsiiProperty(name: "escalations", typeJson: "{\"union\":{\"types\":[{\"fqn\":\"@alicloud/ros-cdk-core.IResolvable\"},{\"fqn\":\"@alicloud/ros-cdk-cms.RosGroupMetricRule.EscalationsProperty\"}]}}", isOverride: true)]
        public object Escalations
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: groupId: The ID of application group.
        /// </remarks>
        [JsiiProperty(name: "groupId", typeJson: "{\"primitive\":\"string\"}", isOverride: true)]
        public string GroupId
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: metricName: The name of the metric. For more information, call DescribeMetricMetaList or see Preset metrics reference.
        /// </remarks>
        [JsiiProperty(name: "metricName", typeJson: "{\"primitive\":\"string\"}", isOverride: true)]
        public string MetricName
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: namespace: The data namespace of the service. For more information, call DescribeMetricMetaList
        /// or see Preset metrics reference.
        /// </remarks>
        [JsiiProperty(name: "namespace", typeJson: "{\"primitive\":\"string\"}", isOverride: true)]
        public string Namespace
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: ruleId: The ID of the alert rule. The IDs of alert rules are generated by callers to ensure
        /// uniqueness.
        /// </remarks>
        [JsiiProperty(name: "ruleId", typeJson: "{\"primitive\":\"string\"}", isOverride: true)]
        public string RuleId
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: ruleName: The name of the alert rule.
        /// </remarks>
        [JsiiProperty(name: "ruleName", typeJson: "{\"primitive\":\"string\"}", isOverride: true)]
        public string RuleName
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: dimensions: The expended resource dimensions.
        /// </remarks>
        [JsiiOptional]
        [JsiiProperty(name: "dimensions", typeJson: "{\"primitive\":\"string\"}", isOptional: true, isOverride: true)]
        public string? Dimensions
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: effectiveInterval: The period when the alert rule is effective.
        /// </remarks>
        [JsiiOptional]
        [JsiiProperty(name: "effectiveInterval", typeJson: "{\"primitive\":\"string\"}", isOptional: true, isOverride: true)]
        public string? EffectiveInterval
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: emailSubject: The subject of the alert notification email.
        /// </remarks>
        [JsiiOptional]
        [JsiiProperty(name: "emailSubject", typeJson: "{\"primitive\":\"string\"}", isOptional: true, isOverride: true)]
        public string? EmailSubject
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: interval: The detection period of alerts.
        /// </remarks>
        [JsiiOptional]
        [JsiiProperty(name: "interval", typeJson: "{\"primitive\":\"number\"}", isOptional: true, isOverride: true)]
        public double? Interval
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: noEffectiveInterval: The period when the alert rule is ineffective.
        /// </remarks>
        [JsiiOptional]
        [JsiiProperty(name: "noEffectiveInterval", typeJson: "{\"primitive\":\"string\"}", isOptional: true, isOverride: true)]
        public string? NoEffectiveInterval
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: period: The aggregation period. Unite: second.
        /// </remarks>
        [JsiiOptional]
        [JsiiProperty(name: "period", typeJson: "{\"primitive\":\"number\"}", isOptional: true, isOverride: true)]
        public double? Period
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: silenceTime: The duration of the mute period during which new alerts are not sent even if the trigger
        /// conditions are met. Unit: second. Default value: 86400. Minimum value: 60.
        /// </remarks>
        [JsiiOptional]
        [JsiiProperty(name: "silenceTime", typeJson: "{\"primitive\":\"number\"}", isOptional: true, isOverride: true)]
        public double? SilenceTime
        {
            get;
            set;
        }

        /// <remarks>
        /// <strong>Property</strong>: webhook: The URL of the callback triggered when an alert occurs.
        /// </remarks>
        [JsiiOptional]
        [JsiiProperty(name: "webhook", typeJson: "{\"primitive\":\"string\"}", isOptional: true, isOverride: true)]
        public string? Webhook
        {
            get;
            set;
        }
    }
}
