package alicloudroscdkga

import (
	_init_ "github.com/alibabacloud-go/ros-cdk/alicloudroscdkga/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkcore"
	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkga/internal"
	"github.com/aws/constructs-go/constructs/v3"
)

// This class encapsulates and extends the ROS resource type `ALIYUN::GA::BandwidthPackage`, which is used to create a bandwidth plan.
type BandwidthPackage interface {
	alicloudroscdkcore.Resource
	// Attribute AutoPay: The AutoPay of the bandwidth.
	AttrAutoPay() alicloudroscdkcore.IResolvable
	// Attribute AutoUseCoupon: The AutoUseCoupon  of the bandwidth.
	AttrAutoUseCoupon() alicloudroscdkcore.IResolvable
	// Attribute Bandwidth: The bandwidth provided by the bandwidth plan.
	AttrBandwidth() alicloudroscdkcore.IResolvable
	// Attribute BandwidthPackageId: The Resource ID of the bandwidth.
	AttrBandwidthPackageId() alicloudroscdkcore.IResolvable
	// Attribute BandwidthPackageName: The Resource name of the bandwidth.
	AttrBandwidthPackageName() alicloudroscdkcore.IResolvable
	// Attribute BandwidthType: the bandwidth BandwidthType of the bandwidth.
	AttrBandwidthType() alicloudroscdkcore.IResolvable
	// Attribute BillingType: The BillingType of the bandwidth.
	AttrBillingType() alicloudroscdkcore.IResolvable
	// Attribute CbnGeographicRegionIdA: The CbnGeographicRegionIdA  of the bandwidth.
	AttrCbnGeographicRegionIdA() alicloudroscdkcore.IResolvable
	// Attribute CbnGeographicRegionIdB: The CbnGeographicRegionIdB of the bandwidth.
	AttrCbnGeographicRegionIdB() alicloudroscdkcore.IResolvable
	// Attribute ChargeType: The ChargeType of the bandwidth.
	AttrChargeType() alicloudroscdkcore.IResolvable
	// Attribute PaymentType: The Payment Type of the bandwidth.
	AttrPaymentType() alicloudroscdkcore.IResolvable
	// Attribute Ratio: The Ratio of the bandwidth.
	AttrRatio() alicloudroscdkcore.IResolvable
	// Attribute Type: The type of the bandwidth plan.
	AttrType() alicloudroscdkcore.IResolvable
	EnableResourcePropertyConstraint() *bool
	SetEnableResourcePropertyConstraint(val *bool)
	Id() *string
	SetId(val *string)
	// The construct tree node associated with this construct.
	Node() alicloudroscdkcore.ConstructNode
	// Returns a string-encoded token that resolves to the physical name that should be passed to the ROS resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by ROS
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	Props() *BandwidthPackageProps
	SetProps(val *BandwidthPackageProps)
	Ref() *string
	Resource() alicloudroscdkcore.RosResource
	SetResource(val alicloudroscdkcore.RosResource)
	Scope() alicloudroscdkcore.Construct
	SetScope(val alicloudroscdkcore.Construct)
	// The stack in which this resource is defined.
	Stack() alicloudroscdkcore.Stack
	AddCondition(condition alicloudroscdkcore.RosCondition)
	AddCount(count interface{})
	AddDependency(resource alicloudroscdkcore.Resource)
	AddResourceDesc(desc *string)
	ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy)
	GeneratePhysicalName() *string
	GetAtt(name *string) alicloudroscdkcore.IResolvable
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	OnValidate() *[]*string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	Prepare()
	SetMetadata(key *string, value interface{})
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	Synthesize(session alicloudroscdkcore.ISynthesisSession)
	// Returns a string representation of this construct.
	ToString() *string
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	Validate() *[]*string
}

// The jsii proxy struct for BandwidthPackage
type jsiiProxy_BandwidthPackage struct {
	internal.Type__alicloudroscdkcoreResource
}

func (j *jsiiProxy_BandwidthPackage) AttrAutoPay() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrAutoPay",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) AttrAutoUseCoupon() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrAutoUseCoupon",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) AttrBandwidth() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrBandwidth",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) AttrBandwidthPackageId() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrBandwidthPackageId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) AttrBandwidthPackageName() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrBandwidthPackageName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) AttrBandwidthType() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrBandwidthType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) AttrBillingType() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrBillingType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) AttrCbnGeographicRegionIdA() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrCbnGeographicRegionIdA",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) AttrCbnGeographicRegionIdB() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrCbnGeographicRegionIdB",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) AttrChargeType() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrChargeType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) AttrPaymentType() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrPaymentType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) AttrRatio() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrRatio",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) AttrType() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) EnableResourcePropertyConstraint() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"enableResourcePropertyConstraint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) Id() *string {
	var returns *string
	_jsii_.Get(
		j,
		"id",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) Node() alicloudroscdkcore.ConstructNode {
	var returns alicloudroscdkcore.ConstructNode
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) Props() *BandwidthPackageProps {
	var returns *BandwidthPackageProps
	_jsii_.Get(
		j,
		"props",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) Ref() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ref",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) Resource() alicloudroscdkcore.RosResource {
	var returns alicloudroscdkcore.RosResource
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) Scope() alicloudroscdkcore.Construct {
	var returns alicloudroscdkcore.Construct
	_jsii_.Get(
		j,
		"scope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BandwidthPackage) Stack() alicloudroscdkcore.Stack {
	var returns alicloudroscdkcore.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewBandwidthPackage(scope alicloudroscdkcore.Construct, id *string, props *BandwidthPackageProps, enableResourcePropertyConstraint *bool) BandwidthPackage {
	_init_.Initialize()

	if err := validateNewBandwidthPackageParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_BandwidthPackage{}

	_jsii_.Create(
		"@alicloud/ros-cdk-ga.BandwidthPackage",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		&j,
	)

	return &j
}

// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewBandwidthPackage_Override(b BandwidthPackage, scope alicloudroscdkcore.Construct, id *string, props *BandwidthPackageProps, enableResourcePropertyConstraint *bool) {
	_init_.Initialize()

	_jsii_.Create(
		"@alicloud/ros-cdk-ga.BandwidthPackage",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		b,
	)
}

func (j *jsiiProxy_BandwidthPackage)SetEnableResourcePropertyConstraint(val *bool) {
	if err := j.validateSetEnableResourcePropertyConstraintParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"enableResourcePropertyConstraint",
		val,
	)
}

func (j *jsiiProxy_BandwidthPackage)SetId(val *string) {
	if err := j.validateSetIdParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"id",
		val,
	)
}

func (j *jsiiProxy_BandwidthPackage)SetProps(val *BandwidthPackageProps) {
	if err := j.validateSetPropsParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"props",
		val,
	)
}

func (j *jsiiProxy_BandwidthPackage)SetResource(val alicloudroscdkcore.RosResource) {
	_jsii_.Set(
		j,
		"resource",
		val,
	)
}

func (j *jsiiProxy_BandwidthPackage)SetScope(val alicloudroscdkcore.Construct) {
	if err := j.validateSetScopeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"scope",
		val,
	)
}

// Return whether the given object is a Construct.
func BandwidthPackage_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateBandwidthPackage_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@alicloud/ros-cdk-ga.BandwidthPackage",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BandwidthPackage) AddCondition(condition alicloudroscdkcore.RosCondition) {
	if err := b.validateAddConditionParameters(condition); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"addCondition",
		[]interface{}{condition},
	)
}

func (b *jsiiProxy_BandwidthPackage) AddCount(count interface{}) {
	if err := b.validateAddCountParameters(count); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"addCount",
		[]interface{}{count},
	)
}

func (b *jsiiProxy_BandwidthPackage) AddDependency(resource alicloudroscdkcore.Resource) {
	if err := b.validateAddDependencyParameters(resource); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"addDependency",
		[]interface{}{resource},
	)
}

func (b *jsiiProxy_BandwidthPackage) AddResourceDesc(desc *string) {
	if err := b.validateAddResourceDescParameters(desc); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"addResourceDesc",
		[]interface{}{desc},
	)
}

func (b *jsiiProxy_BandwidthPackage) ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy) {
	if err := b.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (b *jsiiProxy_BandwidthPackage) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		b,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BandwidthPackage) GetAtt(name *string) alicloudroscdkcore.IResolvable {
	if err := b.validateGetAttParameters(name); err != nil {
		panic(err)
	}
	var returns alicloudroscdkcore.IResolvable

	_jsii_.Invoke(
		b,
		"getAtt",
		[]interface{}{name},
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BandwidthPackage) OnPrepare() {
	_jsii_.InvokeVoid(
		b,
		"onPrepare",
		nil, // no parameters
	)
}

func (b *jsiiProxy_BandwidthPackage) OnSynthesize(session constructs.ISynthesisSession) {
	if err := b.validateOnSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (b *jsiiProxy_BandwidthPackage) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		b,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BandwidthPackage) Prepare() {
	_jsii_.InvokeVoid(
		b,
		"prepare",
		nil, // no parameters
	)
}

func (b *jsiiProxy_BandwidthPackage) SetMetadata(key *string, value interface{}) {
	if err := b.validateSetMetadataParameters(key, value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"setMetadata",
		[]interface{}{key, value},
	)
}

func (b *jsiiProxy_BandwidthPackage) Synthesize(session alicloudroscdkcore.ISynthesisSession) {
	if err := b.validateSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"synthesize",
		[]interface{}{session},
	)
}

func (b *jsiiProxy_BandwidthPackage) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		b,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BandwidthPackage) Validate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		b,
		"validate",
		nil, // no parameters
		&returns,
	)

	return returns
}

