package datasource

import (
	_init_ "github.com/alibabacloud-go/ros-cdk/alicloudroscdkvpc/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkcore"
	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkvpc/datasource/internal"
	"github.com/aws/constructs-go/constructs/v3"
)

// This class encapsulates and extends the ROS resource type `DATASOURCE::VPC::BgpPeer`, which is used to query the information about a Border Gateway Protocol (BGP) peer in a region.
type BgpPeer interface {
	alicloudroscdkcore.Resource
	IBgpPeer
	// Attribute AdvertisedRouteCount: The number of advertised routes.
	AttrAdvertisedRouteCount() interface{}
	// Attribute AuthKey: The authentication key of the BGP group.
	AttrAuthKey() interface{}
	// Attribute BfdMultiHop: The Bidirectional Forwarding Detection (BFD) hop count.
	AttrBfdMultiHop() interface{}
	// Attribute BgpGroupId: The ID of the BGP group.
	AttrBgpGroupId() interface{}
	// Attribute BgpPeerId: The ID of the BGP peer.
	AttrBgpPeerId() interface{}
	// Attribute BgpStatus: The status of the BGP connection.
	//
	// Valid values:
	// Idle: The BGP connection is not used.
	// Connect: The BGP connection is used.
	// Active: The BGP connection is available.
	// Established: The BGP connection is established.
	// Down: The BGP connection is unavailable.
	AttrBgpStatus() interface{}
	// Attribute Description: The description of the BGP group.
	AttrDescription() interface{}
	// Attribute EnableBfd: Indicates whether BFD is enabled.
	//
	// Valid values:
	// false
	// true.
	AttrEnableBfd() interface{}
	// Attribute GmtModified: The time when the BGP peer is modified.
	AttrGmtModified() interface{}
	// Attribute Hold: The hold time.
	AttrHold() interface{}
	// Attribute IpVersion: The version of the IP address.
	AttrIpVersion() interface{}
	// Attribute IsFake: Indicates whether a fake autonomous system number (ASN) is used.
	//
	// Valid values:
	// false
	// true.
	AttrIsFake() interface{}
	// Attribute Keepalive: The Keepalive interval.
	AttrKeepalive() interface{}
	// Attribute LocalAsn: The ASN of the device on the Alibaba Cloud side.
	AttrLocalAsn() interface{}
	// Attribute Name: The name of the BGP peer.
	AttrName() interface{}
	// Attribute PeerAsn: The autonomous system number (ASN)of the BGP peer.
	AttrPeerAsn() interface{}
	// Attribute PeerIpAddress: The IP address of the BGP peer.
	AttrPeerIpAddress() interface{}
	// Attribute ReceivedRouteCount: The number of received routes.
	AttrReceivedRouteCount() interface{}
	// Attribute RouteLimit: The maximum number of routes.
	AttrRouteLimit() interface{}
	// Attribute RouterId: The Router ID.
	AttrRouterId() interface{}
	// Attribute Status: The status of the BGP peer.
	//
	// Valid values:
	// Pending
	// Available
	// Modifying
	// Deleting
	// Deleted.
	AttrStatus() interface{}
	EnableResourcePropertyConstraint() *bool
	SetEnableResourcePropertyConstraint(val *bool)
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *alicloudroscdkcore.ResourceEnvironment
	Id() *string
	SetId(val *string)
	// The construct tree node associated with this construct.
	Node() alicloudroscdkcore.ConstructNode
	// Returns a string-encoded token that resolves to the physical name that should be passed to the ROS resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by ROS
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	Props() *BgpPeerProps
	Ref() *string
	Resource() alicloudroscdkcore.RosResource
	SetResource(val alicloudroscdkcore.RosResource)
	Scope() alicloudroscdkcore.Construct
	SetScope(val alicloudroscdkcore.Construct)
	// The stack in which this resource is defined.
	Stack() alicloudroscdkcore.Stack
	AddCondition(condition alicloudroscdkcore.RosCondition)
	AddCount(count interface{})
	AddDependency(resource alicloudroscdkcore.Resource)
	AddResourceDesc(desc *string)
	ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy)
	FetchCondition() alicloudroscdkcore.RosCondition
	FetchDependency() *[]*string
	FetchResourceDesc() *string
	GeneratePhysicalName() *string
	GetAtt(name *string) alicloudroscdkcore.IResolvable
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	OnValidate() *[]*string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	Prepare()
	SetMetadata(key *string, value interface{})
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	Synthesize(session alicloudroscdkcore.ISynthesisSession)
	// Returns a string representation of this construct.
	ToString() *string
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	Validate() *[]*string
}

// The jsii proxy struct for BgpPeer
type jsiiProxy_BgpPeer struct {
	internal.Type__alicloudroscdkcoreResource
	jsiiProxy_IBgpPeer
}

func (j *jsiiProxy_BgpPeer) AttrAdvertisedRouteCount() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrAdvertisedRouteCount",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrAuthKey() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrAuthKey",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrBfdMultiHop() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrBfdMultiHop",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrBgpGroupId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrBgpGroupId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrBgpPeerId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrBgpPeerId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrBgpStatus() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrBgpStatus",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrDescription() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrDescription",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrEnableBfd() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrEnableBfd",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrGmtModified() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrGmtModified",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrHold() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrHold",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrIpVersion() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrIpVersion",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrIsFake() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrIsFake",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrKeepalive() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrKeepalive",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrLocalAsn() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrLocalAsn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrName() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrPeerAsn() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrPeerAsn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrPeerIpAddress() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrPeerIpAddress",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrReceivedRouteCount() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrReceivedRouteCount",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrRouteLimit() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrRouteLimit",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrRouterId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrRouterId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) AttrStatus() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrStatus",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) EnableResourcePropertyConstraint() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"enableResourcePropertyConstraint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) Env() *alicloudroscdkcore.ResourceEnvironment {
	var returns *alicloudroscdkcore.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) Id() *string {
	var returns *string
	_jsii_.Get(
		j,
		"id",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) Node() alicloudroscdkcore.ConstructNode {
	var returns alicloudroscdkcore.ConstructNode
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) Props() *BgpPeerProps {
	var returns *BgpPeerProps
	_jsii_.Get(
		j,
		"props",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) Ref() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ref",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) Resource() alicloudroscdkcore.RosResource {
	var returns alicloudroscdkcore.RosResource
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) Scope() alicloudroscdkcore.Construct {
	var returns alicloudroscdkcore.Construct
	_jsii_.Get(
		j,
		"scope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BgpPeer) Stack() alicloudroscdkcore.Stack {
	var returns alicloudroscdkcore.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewBgpPeer(scope alicloudroscdkcore.Construct, id *string, props *BgpPeerProps, enableResourcePropertyConstraint *bool) BgpPeer {
	_init_.Initialize()

	if err := validateNewBgpPeerParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_BgpPeer{}

	_jsii_.Create(
		"@alicloud/ros-cdk-vpc.datasource.BgpPeer",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		&j,
	)

	return &j
}

// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewBgpPeer_Override(b BgpPeer, scope alicloudroscdkcore.Construct, id *string, props *BgpPeerProps, enableResourcePropertyConstraint *bool) {
	_init_.Initialize()

	_jsii_.Create(
		"@alicloud/ros-cdk-vpc.datasource.BgpPeer",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		b,
	)
}

func (j *jsiiProxy_BgpPeer)SetEnableResourcePropertyConstraint(val *bool) {
	if err := j.validateSetEnableResourcePropertyConstraintParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"enableResourcePropertyConstraint",
		val,
	)
}

func (j *jsiiProxy_BgpPeer)SetId(val *string) {
	if err := j.validateSetIdParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"id",
		val,
	)
}

func (j *jsiiProxy_BgpPeer)SetResource(val alicloudroscdkcore.RosResource) {
	_jsii_.Set(
		j,
		"resource",
		val,
	)
}

func (j *jsiiProxy_BgpPeer)SetScope(val alicloudroscdkcore.Construct) {
	if err := j.validateSetScopeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"scope",
		val,
	)
}

// Return whether the given object is a Construct.
func BgpPeer_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateBgpPeer_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@alicloud/ros-cdk-vpc.datasource.BgpPeer",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BgpPeer) AddCondition(condition alicloudroscdkcore.RosCondition) {
	if err := b.validateAddConditionParameters(condition); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"addCondition",
		[]interface{}{condition},
	)
}

func (b *jsiiProxy_BgpPeer) AddCount(count interface{}) {
	if err := b.validateAddCountParameters(count); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"addCount",
		[]interface{}{count},
	)
}

func (b *jsiiProxy_BgpPeer) AddDependency(resource alicloudroscdkcore.Resource) {
	if err := b.validateAddDependencyParameters(resource); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"addDependency",
		[]interface{}{resource},
	)
}

func (b *jsiiProxy_BgpPeer) AddResourceDesc(desc *string) {
	if err := b.validateAddResourceDescParameters(desc); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"addResourceDesc",
		[]interface{}{desc},
	)
}

func (b *jsiiProxy_BgpPeer) ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy) {
	if err := b.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (b *jsiiProxy_BgpPeer) FetchCondition() alicloudroscdkcore.RosCondition {
	var returns alicloudroscdkcore.RosCondition

	_jsii_.Invoke(
		b,
		"fetchCondition",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BgpPeer) FetchDependency() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		b,
		"fetchDependency",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BgpPeer) FetchResourceDesc() *string {
	var returns *string

	_jsii_.Invoke(
		b,
		"fetchResourceDesc",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BgpPeer) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		b,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BgpPeer) GetAtt(name *string) alicloudroscdkcore.IResolvable {
	if err := b.validateGetAttParameters(name); err != nil {
		panic(err)
	}
	var returns alicloudroscdkcore.IResolvable

	_jsii_.Invoke(
		b,
		"getAtt",
		[]interface{}{name},
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BgpPeer) OnPrepare() {
	_jsii_.InvokeVoid(
		b,
		"onPrepare",
		nil, // no parameters
	)
}

func (b *jsiiProxy_BgpPeer) OnSynthesize(session constructs.ISynthesisSession) {
	if err := b.validateOnSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (b *jsiiProxy_BgpPeer) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		b,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BgpPeer) Prepare() {
	_jsii_.InvokeVoid(
		b,
		"prepare",
		nil, // no parameters
	)
}

func (b *jsiiProxy_BgpPeer) SetMetadata(key *string, value interface{}) {
	if err := b.validateSetMetadataParameters(key, value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"setMetadata",
		[]interface{}{key, value},
	)
}

func (b *jsiiProxy_BgpPeer) Synthesize(session alicloudroscdkcore.ISynthesisSession) {
	if err := b.validateSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"synthesize",
		[]interface{}{session},
	)
}

func (b *jsiiProxy_BgpPeer) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		b,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BgpPeer) Validate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		b,
		"validate",
		nil, // no parameters
		&returns,
	)

	return returns
}

