package alicloudroscdkess

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkcore"
	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkess/internal"
)

// Represents a `ScheduledTask`.
type IScheduledTask interface {
	alicloudroscdkcore.IResource
	// Attribute ScheduledTaskId: ID of the scheduled task, which is generated by the system and globally unique.
	AttrScheduledTaskId() interface{}
	Props() *ScheduledTaskProps
}

// The jsii proxy for IScheduledTask
type jsiiProxy_IScheduledTask struct {
	internal.Type__alicloudroscdkcoreIResource
}

func (j *jsiiProxy_IScheduledTask) AttrScheduledTaskId() interface{} {
	var returns interface{}
	_jsii_.Get(
		j,
		"attrScheduledTaskId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IScheduledTask) Props() *ScheduledTaskProps {
	var returns *ScheduledTaskProps
	_jsii_.Get(
		j,
		"props",
		&returns,
	)
	return returns
}

