package datasource

import (
	_init_ "github.com/alibabacloud-go/ros-cdk/alicloudroscdkpolardb/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkcore"
	"github.com/alibabacloud-go/ros-cdk/alicloudroscdkpolardb/datasource/internal"
	"github.com/aws/constructs-go/constructs/v3"
)

// This class encapsulates and extends the ROS resource type `DATASOURCE::POLARDB::GlobalDatabaseNetwork`.
type GlobalDatabaseNetwork interface {
	alicloudroscdkcore.Resource
	// Attribute Connections: The information about the connection to the cluster.
	AttrConnections() alicloudroscdkcore.IResolvable
	// Attribute CreateTime: The time at which the GDN was created.
	AttrCreateTime() alicloudroscdkcore.IResolvable
	// Attribute DbClusters: The clusters that are included in the GDN.
	AttrDbClusters() alicloudroscdkcore.IResolvable
	// Attribute DbType: The type of the database engine.
	//
	// Only MySQL is supported.
	AttrDbType() alicloudroscdkcore.IResolvable
	// Attribute DbVersion: The version of the database engine.
	//
	// Only version 8.0 is supported.
	AttrDbVersion() alicloudroscdkcore.IResolvable
	// Attribute GdnDescription: The description of the GDN.
	//
	// The description must meet the following requirements:
	// It cannot start with http:// or https://.
	// It must start with a letter.
	// It can contain letters, digits, underscores (_), and hyphens (-).
	// It must be 2 to 126 characters in length.
	AttrGdnDescription() alicloudroscdkcore.IResolvable
	// Attribute GdnId: The ID of the GDN.
	AttrGdnId() alicloudroscdkcore.IResolvable
	EnableResourcePropertyConstraint() *bool
	SetEnableResourcePropertyConstraint(val *bool)
	Id() *string
	SetId(val *string)
	// The construct tree node associated with this construct.
	Node() alicloudroscdkcore.ConstructNode
	// Returns a string-encoded token that resolves to the physical name that should be passed to the ROS resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by ROS
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	Props() *GlobalDatabaseNetworkProps
	SetProps(val *GlobalDatabaseNetworkProps)
	Ref() *string
	Resource() alicloudroscdkcore.RosResource
	SetResource(val alicloudroscdkcore.RosResource)
	Scope() alicloudroscdkcore.Construct
	SetScope(val alicloudroscdkcore.Construct)
	// The stack in which this resource is defined.
	Stack() alicloudroscdkcore.Stack
	AddCondition(condition alicloudroscdkcore.RosCondition)
	AddCount(count interface{})
	AddDependency(resource alicloudroscdkcore.Resource)
	AddResourceDesc(desc *string)
	ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy)
	GeneratePhysicalName() *string
	GetAtt(name *string) alicloudroscdkcore.IResolvable
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	OnValidate() *[]*string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	Prepare()
	SetMetadata(key *string, value interface{})
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	Synthesize(session alicloudroscdkcore.ISynthesisSession)
	// Returns a string representation of this construct.
	ToString() *string
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	Validate() *[]*string
}

// The jsii proxy struct for GlobalDatabaseNetwork
type jsiiProxy_GlobalDatabaseNetwork struct {
	internal.Type__alicloudroscdkcoreResource
}

func (j *jsiiProxy_GlobalDatabaseNetwork) AttrConnections() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrConnections",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) AttrCreateTime() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrCreateTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) AttrDbClusters() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrDbClusters",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) AttrDbType() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrDbType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) AttrDbVersion() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrDbVersion",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) AttrGdnDescription() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrGdnDescription",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) AttrGdnId() alicloudroscdkcore.IResolvable {
	var returns alicloudroscdkcore.IResolvable
	_jsii_.Get(
		j,
		"attrGdnId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) EnableResourcePropertyConstraint() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"enableResourcePropertyConstraint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) Id() *string {
	var returns *string
	_jsii_.Get(
		j,
		"id",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) Node() alicloudroscdkcore.ConstructNode {
	var returns alicloudroscdkcore.ConstructNode
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) Props() *GlobalDatabaseNetworkProps {
	var returns *GlobalDatabaseNetworkProps
	_jsii_.Get(
		j,
		"props",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) Ref() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ref",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) Resource() alicloudroscdkcore.RosResource {
	var returns alicloudroscdkcore.RosResource
	_jsii_.Get(
		j,
		"resource",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) Scope() alicloudroscdkcore.Construct {
	var returns alicloudroscdkcore.Construct
	_jsii_.Get(
		j,
		"scope",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_GlobalDatabaseNetwork) Stack() alicloudroscdkcore.Stack {
	var returns alicloudroscdkcore.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewGlobalDatabaseNetwork(scope alicloudroscdkcore.Construct, id *string, props *GlobalDatabaseNetworkProps, enableResourcePropertyConstraint *bool) GlobalDatabaseNetwork {
	_init_.Initialize()

	if err := validateNewGlobalDatabaseNetworkParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_GlobalDatabaseNetwork{}

	_jsii_.Create(
		"@alicloud/ros-cdk-polardb.datasource.GlobalDatabaseNetwork",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		&j,
	)

	return &j
}

// Param scope - scope in which this resource is defined Param id    - scoped id of the resource Param props - resource properties.
func NewGlobalDatabaseNetwork_Override(g GlobalDatabaseNetwork, scope alicloudroscdkcore.Construct, id *string, props *GlobalDatabaseNetworkProps, enableResourcePropertyConstraint *bool) {
	_init_.Initialize()

	_jsii_.Create(
		"@alicloud/ros-cdk-polardb.datasource.GlobalDatabaseNetwork",
		[]interface{}{scope, id, props, enableResourcePropertyConstraint},
		g,
	)
}

func (j *jsiiProxy_GlobalDatabaseNetwork)SetEnableResourcePropertyConstraint(val *bool) {
	if err := j.validateSetEnableResourcePropertyConstraintParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"enableResourcePropertyConstraint",
		val,
	)
}

func (j *jsiiProxy_GlobalDatabaseNetwork)SetId(val *string) {
	if err := j.validateSetIdParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"id",
		val,
	)
}

func (j *jsiiProxy_GlobalDatabaseNetwork)SetProps(val *GlobalDatabaseNetworkProps) {
	if err := j.validateSetPropsParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"props",
		val,
	)
}

func (j *jsiiProxy_GlobalDatabaseNetwork)SetResource(val alicloudroscdkcore.RosResource) {
	_jsii_.Set(
		j,
		"resource",
		val,
	)
}

func (j *jsiiProxy_GlobalDatabaseNetwork)SetScope(val alicloudroscdkcore.Construct) {
	if err := j.validateSetScopeParameters(val); err != nil {
		panic(err)
	}
	_jsii_.Set(
		j,
		"scope",
		val,
	)
}

// Return whether the given object is a Construct.
func GlobalDatabaseNetwork_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateGlobalDatabaseNetwork_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@alicloud/ros-cdk-polardb.datasource.GlobalDatabaseNetwork",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GlobalDatabaseNetwork) AddCondition(condition alicloudroscdkcore.RosCondition) {
	if err := g.validateAddConditionParameters(condition); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"addCondition",
		[]interface{}{condition},
	)
}

func (g *jsiiProxy_GlobalDatabaseNetwork) AddCount(count interface{}) {
	if err := g.validateAddCountParameters(count); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"addCount",
		[]interface{}{count},
	)
}

func (g *jsiiProxy_GlobalDatabaseNetwork) AddDependency(resource alicloudroscdkcore.Resource) {
	if err := g.validateAddDependencyParameters(resource); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"addDependency",
		[]interface{}{resource},
	)
}

func (g *jsiiProxy_GlobalDatabaseNetwork) AddResourceDesc(desc *string) {
	if err := g.validateAddResourceDescParameters(desc); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"addResourceDesc",
		[]interface{}{desc},
	)
}

func (g *jsiiProxy_GlobalDatabaseNetwork) ApplyRemovalPolicy(policy alicloudroscdkcore.RemovalPolicy) {
	if err := g.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (g *jsiiProxy_GlobalDatabaseNetwork) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		g,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GlobalDatabaseNetwork) GetAtt(name *string) alicloudroscdkcore.IResolvable {
	if err := g.validateGetAttParameters(name); err != nil {
		panic(err)
	}
	var returns alicloudroscdkcore.IResolvable

	_jsii_.Invoke(
		g,
		"getAtt",
		[]interface{}{name},
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GlobalDatabaseNetwork) OnPrepare() {
	_jsii_.InvokeVoid(
		g,
		"onPrepare",
		nil, // no parameters
	)
}

func (g *jsiiProxy_GlobalDatabaseNetwork) OnSynthesize(session constructs.ISynthesisSession) {
	if err := g.validateOnSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (g *jsiiProxy_GlobalDatabaseNetwork) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		g,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GlobalDatabaseNetwork) Prepare() {
	_jsii_.InvokeVoid(
		g,
		"prepare",
		nil, // no parameters
	)
}

func (g *jsiiProxy_GlobalDatabaseNetwork) SetMetadata(key *string, value interface{}) {
	if err := g.validateSetMetadataParameters(key, value); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"setMetadata",
		[]interface{}{key, value},
	)
}

func (g *jsiiProxy_GlobalDatabaseNetwork) Synthesize(session alicloudroscdkcore.ISynthesisSession) {
	if err := g.validateSynthesizeParameters(session); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		g,
		"synthesize",
		[]interface{}{session},
	)
}

func (g *jsiiProxy_GlobalDatabaseNetwork) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		g,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (g *jsiiProxy_GlobalDatabaseNetwork) Validate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		g,
		"validate",
		nil, // no parameters
		&returns,
	)

	return returns
}

